### ISSUE TITLE
Two minor discrepancies with the AlphaFold paper

### ISSUE THREAD

**Issue by empyriumz** [aqlaboratory/openfold#105]
Hi there,

I spotted two minor discrepancies with the AlphaFold's paper. I'm not sure if they are intended or mistaken.

1. In the `"recycling_embedder"` (in `openfold/config.py`), the default values of`min_bin` and `max_bin` are set to 3.25 and 20.75, respectively. While in the AlphaFold's paper they are 3.375 and 21.375 instead (See Supplemental material p.43, texts above Algorithm 32)
2. The default `"max_recycling_iters"` is 3. However the actual recycling dimension is `max_recycling_iters + 1`. See line 186-188 [here](https://github.com/aqlaboratory/openfold/blob/main/openfold/data/input_pipeline.py#L186) in the `openfold/data/nput_pipeline.py`. 

Thank you in advance :)

**Comment by gahdritz** [comment]
Hello,

Thanks for taking such a close look at OpenFold! It's great to know that there are additional pairs of eyes on this thing.

Both of these discrepancies are intended:

1. This is actually a discrepancy between the AlphaFold supplement and the AlphaFold source code. See https://github.com/deepmind/alphafold/blob/1d43aaff941c84dc56311076b58795797e49107b/alphafold/model/config.py#L256.
2. By `max_recycling_iters`, I mean the number of _additional_ iterations, excluding the final, default iteration. So `max_recycling_iters=0` implies that no recycling takes place, and that just one pass through the model takes place. Therefore, the default value of 3 causes 4 total iterations to take place, as in AlphaFold.

**Comment by empyriumz** [comment]
@gahdritz Thanks for your prompt reply! 
I didn't check AlphaFold's code for the 1st one, and now I get it.

For the 2nd issue, do you mean that recycling `n` times = total `n+1` iterations?
In AlphaFold's paper, it mentions the default recycling is 3 times. In the supplemental material (p. 42, Algorithm 30), if I understand correctly, `N_cycle` there denotes the total # of iterations. I guess my confusion results from the nomenclature.

**Comment by gahdritz** [comment]
That's right. See e.g. section 1.10, page 41 of the AlphaFold supplement, where DeepMind gives `N_cycle = 4`, the same as the total number of iterations OpenFold runs.

**Comment by empyriumz** [comment]
Oh I see. Sorry I didn't go through the whole texts:)
