### ISSUE TITLE
Is checkpoint_blocks used properly?

### ISSUE THREAD

**Issue by zlweb** [aqlaboratory/openfold#109]
Seems checkpoint_blocks is fully used in evoformer forward()
https://github.com/aqlaboratory/openfold/blob/24118e804535515398e77010e11b1312f6ff1b62/openfold/model/evoformer.py#L574

but in first few recycles, grad is disabled, is it still necessary to put checkpoint_blocks there, it may impact performance a bit. 
or add another check together, e.g.

m, z = checkpoint_blocks(
            blocks,
            args=(m, z),
            blocks_per_ckpt=self.blocks_per_ckpt if self.training and torch.is_grad_enabled() else None,
        )

**Comment by gahdritz** [comment]
Good catch. Fixed in a14e83.

**Comment by zlweb** [comment]
same change with me in my local repo.
