### ISSUE TITLE
Confusing training commands in the README

### ISSUE THREAD

**Issue by Zhang690683220** [aqlaboratory/openfold#112]
Hi,

I find that the training commands are not correct which leads to confusion.

1. There should be only 1 `mmcif_dir`, which should be set to `data/pdb_mmcif/mmcif_files/`
2. You have to add the parameter flags to those databases: 
```
--uniref90_database_path=data/uniref90/uniref90.fasta \
--mgnify_database_path=data/mgnify/mgy_clusters_2018_12.fa \
--pdb70_database_path=data/pdb70/pdb70 \
--uniclust30_database_path= data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
```

Please fix the README for the correct usage.

Thanks,

Bo

**Comment by gahdritz** [comment]
Hello,

1. The reason I don't refer specifically to `pdb_mmcif` there is that, unlike the rest of the databases, this one can be swapped out, for any directory of mmCIF files. Furthermore, the reason why I differentiate between `mmcif_dir` and `template_mmcif_dir` is to emphasize that they can be---and, indeed, often are---separate directories.
2. Fixed.
