### ISSUE TITLE
Cannot download the param file

### ISSUE THREAD

**Issue by akichinguyen** [aqlaboratory/openfold#118]
Hi team, I ran the script to download the openfold param file and it gave me error "Google Drive - Quota exceeded". Could you help to resolve it?

**Comment by alquraishi** [comment]
Thanks for bringing this to our attention. Looks like we've maxed out our tokens. We'll get this fixed ASAP!

**Comment by akichinguyen** [comment]
Thank you so much. The link above worked.

**Comment by gahdritz** [comment]
As of a48860c, this is now the default source.
