### ISSUE TITLE
Can openfold achieve AF2 performance?

### ISSUE THREAD

**Issue by jorhelp** [aqlaboratory/openfold#12]
Nice work! Can openfold achieve AF2 performance?

**Comment by alquraishi** [comment]
Our intent/plan is full performance parity with AF2.

**Comment by gahdritz** [comment]
In the meantime, while we train our own weights, you can use AlphaFold's pretrained weights for exact inference parity (i.e. the outputs will be identical up to a maximum pointwise difference of like 1e-4, caused by slight differences in PyTorch's and JAX's arithmetic backends).

**Comment by jorhelp** [comment]
> Our intent/plan is full performance parity with AF2.

👍🏻👍🏻

**Comment by jorhelp** [comment]
> In the meantime, while we train our own weights, you can currently run OpenFold with AlphaFold's pretrained weights for exact inference parity (i.e. the outputs will be identical up to a maximum pointwise difference of like 1e-4, caused by slight differences in PyTorch's and JAX's arithmetic backends).

Great job. Look forward to seeing the model you train outperform AlphaFold2!!
