### ISSUE TITLE
Colab OpenFold issue: Search against genetic databases - NameError: name 'futures' is not defined

### ISSUE THREAD

**Issue by Nachtschatt** [aqlaboratory/openfold#123]
Search against genetic databases gives sequence independent error:

NameError                                 Traceback (most recent call last)
'<'ipython-input-7-97b824ca3486'>' in '<'module'>'()
     15 # --- Find the closest source ---
     16 test_url_pattern = '[https://storage.googleapis.com/alphafold-colab{:s}/latest/uniref90_2021_03.fasta.1](https://storage.googleapis.com/alphafold-colab%7B:s%7D/latest/uniref90_2021_03.fasta.1)'
---> 17 ex = futures.ThreadPoolExecutor(3)
     18 def fetch(source):
     19   request.urlretrieve(test_url_pattern.format(source))

NameError: name 'futures' is not defined

**Comment by SauravMaheshkar** [comment]
Did you edit the notebook anytime ?

Because I didn't encounter this while running the notebook. The futures submodule is imported in the "Import Python packages" Section. viz.

```python
from concurrent import futures
```

**Comment by Nachtschatt** [comment]
Nevermind. I misread the instruction when it says to _run the remaining cells via Runtime > Run after_

_Runtime > Run all_  works. 

Thank  you!
