### ISSUE TITLE
DeepSpeed large checkpoints, training on multi GPU

### ISSUE THREAD

**Issue by CodyLDA** [aqlaboratory/openfold#125]
Hello,

I want to train a model from scratch with some modifications (especially in size) on a multi-node, multi-GPU environment. For that, I am using DeepSpeed, more precisely, the DeepSpeedPlugin with this deep_speed_config.json:
```json
{
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.001,
      "eps": 1e-05
    }
  },
  "fp16": {
    "enabled": false,
    "min_loss_scale": 1
  },
  "amp": {
    "enabled": false,
    "opt_level": "O2"
  },
  "bfloat16": {
    "enabled": false
  },
  "zero_optimization": {
    "stage": 2,
    "cpu_offload": false,
    "contiguous_gradients": true
  },
  "activation_checkpointing": {
    "partition_activations": true,
    "cpu_checkpointing": false,
    "profile": false
  },
  "gradient_clipping": 0.1
}
```
For checkpointing, the files `mp_rank_00_model_states.pt` (9GB), `zero_pp_rank_0_mp_rank_00_optim_states.pt` (13GB), `zero_pp_rank_1_mp_rank_00_optim_states.pt` (13GB), etc (the optimizer checkpoints are written per GPU if I am not mistaken)
The actual needed model weights for inference are obviously smaller since `mp_rank_00_model_states.pt` contains more information.

But now I was wondering, do those files really have to be that huge or is it possible to shrink them down somehow? 
If I train on e.g. 10 GPUs, doesn't that mean I would fill up >100GB of storage just to store one checkpoint to resume training / save the best performing model?
I am currently struggling a bit with this since the writing of a checkpoint takes ages and this means, during that time training is delayed. 
Do you have any suggestions for me or am I just missing some configuration I could potentially set?

Thanks in advance and thank you very much for this great repo!

**Comment by gahdritz** [comment]
My checkpoints aren't nearly that big (just 1.7GB total) and I'm training on 44 GPUs. Have you made any other modifications to the code?

**Comment by CodyLDA** [comment]
Thanks for your quick response and sorry for my late reaction.

Indeed I have changed the architecture and added some modules for research purposes. But that means that you still have to write/store about 75G per checkpoint in total? If so, is there really no way to get around this?

**Comment by gahdritz** [comment]
No, I store 1.7GB per checkpoint in total. I suspect that something is wrong with your version. Are you massively increasing the number of parameters or something.

**Comment by CodyLDA** [comment]
Ohh ... the modules I added to the architecture are quite large, in total I have about 1.2B parameters, should result in checkpoints of size about 5GB if I am not mistaken.
I have also enabled pTM-Score but this should not be that heavy.

As far as I can tell, the 9G is due to the fact that the `mp_rank_00_model_states.pt` does not only contain the actual model weights but also the EMA-version of those --- which are used for inference if, aren't they?
But this still does not explain the huge size of the zero optim states. 
Unfortunately I cannot go down with the number of parameters but from what I have read from DeepSpeed, they usually train with way larger models and don't have any issues.
But it seems like you didn't have to encounter this problem in the first place, still thanks. 

Related question, if I specify the optimizer inside of the DeepSpeed config, is this better than using the configure_optimizers method in the OpenFoldWrapper? What is the recommended way because I receive the UserWarning that I might want to use the PT Lightning call instead of the DeepSpeed config.

**Comment by gahdritz** [comment]
Does it get much smaller if you disable the EMA module (try commenting out every line referencing `self.ema` in `train_openfold.py`)

**Comment by CodyLDA** [comment]
Disabling the EMA cuts the `mp_rank_00_model_states.pt` in half to about 4.5G (this is about expected from what I can tell) but the zero optim states seem to remain unchanged.

What I find odd is that if I use the PTL optimizers (not specifying the optimizers in the DeepSpeed config) the zero optim states seem to stay this large and the model state also does not change in size, is this expected? The strategy is still set to DeepSpeed.

**Comment by gahdritz** [comment]
Yeah that's what I'd expect. Perhaps this is something to bring up with the DeepSpeed devs?

**Comment by CodyLDA** [comment]
Yeah, sounds fair. I am closing this since it does not seem to be caused by Openfold.
