### ISSUE TITLE
scripts/install_hh_suite.sh: line 4: syntax error near unexpected token `&&'

### ISSUE THREAD

**Issue by lucajovine** [aqlaboratory/openfold#129]
> scripts/install_hh_suite.sh
Cloning into '/tmp/hh-suite'...
remote: Enumerating objects: 9214, done.
remote: Counting objects: 100% (634/634), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 9214 (delta 448), reused 622 (delta 444), pack-reused 8580
Receiving objects: 100% (9214/9214), 23.79 MiB | 18.61 MiB/s, done.
Resolving deltas: 100% (6975/6975), done.
Note: switching to '47a835a6329e8041741160c1196bc82d718d56e0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

scripts/install_hh_suite.sh: line 4: syntax error near unexpected token `&&'
scripts/install_hh_suite.sh: line 4: `&& mkdir /tmp/hh-suite/build'
>

**Comment by gahdritz** [comment]
Fixed in a35c44f.
