### ISSUE TITLE
Structure data in dataset

### ISSUE THREAD

**Issue by jamaliki** [aqlaboratory/openfold#136]
Hello all and thank you so much for this repo. I am asking about the training set that was shared on AWS. It seems that it only includes sequence information, was it not also supposed to include predicted structures for those sequences?

**Comment by CodyLDA** [comment]
Hello everyone, any updates here or am I missing something?

**Comment by gahdritz** [comment]
No sorry this is still held up. I expect to upload them this weekend.

**Comment by gahdritz** [comment]
Structures are up.
