### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by tcapelle** [aqlaboratory/openfold#14]
Hey epic work!
Could you post a `Dockerfile` for training/inference? 
Thanks!

**Comment by gahdritz** [comment]
I'll put it on my to-do list, but given that I don't personally have any experience with Docker, a community contribution here would be welcome.

**Comment by tcapelle** [comment]
I will try to do my best tomorrow!

**Comment by RishiKumarRay** [comment]
I can do this, should i start?

**Comment by tcapelle** [comment]
please, I moved to other stuff.

**Comment by mblumberg** [comment]
Curious if anyone's made progress on this? 
-- Would be quite useful...

**Comment by gahdritz** [comment]
@mblumberg See #54

**Comment by mblumberg** [comment]
Thx :+1:
