### ISSUE TITLE
Feature request: flag to optionally output PDBs with 100-pLDDT in B-factor column for MR

### ISSUE THREAD

**Issue by lucajovine** [aqlaboratory/openfold#147]
Hello,
I understand the adherence to heat map formalism but, as things stand, we must all somehow perform this or similar conversions (using own scripts, or tools in PHENIX or CCP4) when post-processing models for molecular replacement.
Since in my experience a simple 100-pLDDT conversion is generally as good as more sophisticated treatments (at least when using AlphaFold2 models), would it be possible to add an OpenFold flag that allows to **optionally** output models with the B-factor column already containing 100-pLDDT (instead of pLDDT)?
Clearly this is not a top priority request, but it would still be useful for non-experienced users and lazy crystallographers alike ;-)
Thanks!

**Comment by lucajovine** [comment]
Hi! In the case of AF2, output PDB files contain a per-residue confidence score (0-100) in their B-factor column, as described in https://alphafold.ebi.ac.uk/faq#faq-5 (where pLDDT = predicted Local- Distance Difference Test,  see page 584 of the 2021 Nature paper by Jumper et al.). The the B-factor values of the models produced by OF are also 0<B<100, so I assume that you are also putting there a confidence score that is similar (or identical) to AF2's?

**Comment by lucajovine** [comment]
If so, this creates a problem for MR because the highest confidence parts of the models are down-weighted by MR software instead of being up-weighted... and an admittedly simplistic (but working) solution to this, is to replace the confidence score in the B factor column with (100 - confidence score).

**Comment by gahdritz** [comment]
Oh I see---that's a subtraction, not a dash. I'll put this on the list.

**Comment by gahdritz** [comment]
Added in 9617306.

**Comment by lucajovine** [comment]
Now tested on my side too, works just fine. Thank you!
