### ISSUE TITLE
What should template_mmcif_dir be?

### ISSUE THREAD

**Issue by panganqi** [aqlaboratory/openfold#15]
For training use ColabFold pipeline (and templates with HHsearch), there is a path **template_mmcif_dir**.
Should it be something like **data/pdb_mmcif/mmcif_files/** or other precomputed folders？

**Comment by gahdritz** [comment]
It should just point to a directory containing mmCIF files corresponding to the sequences in the database on which you ran HHsearch. If you're using pdb70 as that database, then yeah, data/pdb_mmcif/mmcif_files is the way to go.
