### ISSUE TITLE
Stereo chemical props not downloaded by install script

### ISSUE THREAD

**Issue by epenning** [aqlaboratory/openfold#153]
### Expected behavior

Can run `run_pretrained_openfold.py` in a local installation with relaxation to produce a relaxed structure.

### Actual behavior

After following the Readme's installation instructions and executing `run_pretrained_openfold.py`, this error occurs when relaxation starts:

```
FileNotFoundError: [Errno 2] No such file or directory: '<...>/openfold/resources/stereo_chemical_props.txt'
```

### Context

There seems to be caused by a silent error in this quiet line in `install_third_party_dependencies.sh`:

https://github.com/aqlaboratory/openfold/blob/7a5b5835d616e58eee5288971c280ac0b095dc37/scripts/install_third_party_dependencies.sh#L26-L28

Removing the `-q` reveals this error for an expired certificate:

```
Resolving git.scicore.unibas.ch (git.scicore.unibas.ch)... 131.152.229.50
Connecting to git.scicore.unibas.ch (git.scicore.unibas.ch)|131.152.229.50|:443... connected.
ERROR: cannot verify git.scicore.unibas.ch's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to git.scicore.unibas.ch insecurely, use `--no-check-certificate'.
```

**Comment by gahdritz** [comment]
What version of wget are you running? Mine seems to accept the certificate.

**Comment by epenning** [comment]
Interesting, maybe it's just a problem for me then! Looks like I have an old version of wget, 1.14.
