### ISSUE TITLE
Training curves

### ISSUE THREAD

**Issue by lhatsk** [aqlaboratory/openfold#154]
I'm curious what the training curves looked like for you. Are they available by chance? How much did the refinement stage improve the lddt-CA?

Thanks!

**Comment by gahdritz** [comment]
We'll be releasing more details with our preprint, but the refinement stage didn't improve LDDT-Ca much. It did vastly reduce violations, though.

**Comment by lhatsk** [comment]
Ok, thanks! Looking forward to the preprint.
