### ISSUE TITLE
Error parsing .a3m from ColabFold MMseqs2

### ISSUE THREAD

**Issue by epenning** [aqlaboratory/openfold#155]
### Expected behavior:

I can set `--use_precomputed_alignments` with `run_pretrained_openfold.py` to run inference on a monomer using a `.a3m` MSA output file from ColabFold MMseqs2.

### Actual behavior:

This error occurs:

```
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 499, in <module>
    main(args)
  File "run_pretrained_openfold.py", line 352, in main
    args,
  File "run_pretrained_openfold.py", line 195, in generate_feature_dict
    fasta_path=tmp_fasta_path, alignment_dir=local_alignment_dir
  File "<...>/openfold/openfold/data/data_pipeline.py", line 622, in process_fasta
    msa_features = self._process_msa_feats(alignment_dir, input_sequence, alignment_index)
  File "<...>/openfold/openfold/data/data_pipeline.py", line 582, in _process_msa_feats
    alignment_dir, input_sequence, alignment_index
  File "<...>/openfold/openfold/data/data_pipeline.py", line 555, in _get_msas
    msa_data = self._parse_msa_data(alignment_dir, alignment_index)
  File "<...>/openfold/openfold/data/data_pipeline.py", line 502, in _parse_msa_data
    msa, deletion_matrix = parsers.parse_a3m(fp.read())
  File "<...>/openfold/openfold/data/parsers.py", line 145, in parse_a3m
    sequences, _ = parse_fasta(a3m_string)
  File "<...>/openfold/openfold/data/parsers.py", line 65, in parse_fasta
    sequences[index] += line
IndexError: list index out of range
```

### Context:

I used the default placeholder sequence and output MSA from [ColabFold MMseqs2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb):

`fasta_dir/test.fasta`:
```
>test
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK
```
`precomputed_alignments/test/test.a3m`:
```
#59	1
>101
PIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASK
>UPI00143C904E	86	0.396	1.389E-17	0	57	59	1	58	68
PMIHVEMYPGRTPEQKADLVREVTDAFVRTCGGNPDGVWVVIQEVPGEHWGVGGQLAS-
>A0A7C3BUL5	84	0.322	4.949E-17	0	58	59	1	59	60
PLVTVEMWEGRTVEQKKELAQGITSVMTDKLGIPPEAVTIIIKDVPKHNWAIGGKLSSE
>A0A4P6L4R2	83	0.322	1.284E-16	0	58	59	1	59	61
PTINVQLFEGRTPEQKRAFVQAVTQATVETLGSSPESVDIILHEVKREHWATGGKLWSE
...
<rest of file>
...
```

I think the issue is that the ColabFold MMseqs2 `.a3m` format has a first line beginning with `#`, which seems to be some informational line regarding chains in the form `#<chain 1 length>,<chain 2 length>,...  <chain 1 copies>,<chain 2 copies>,...`

In `parsers.py`, `parse_a3m` delegates to `parse_fasta`, which produces the error on non-blank lines occurring before the first `>` line:

https://github.com/aqlaboratory/openfold/blob/d063e344de262b199575896c6e997b6497272353/openfold/data/parsers.py#L57-L65

My workaround has been to skip lines starting with #:
```
 line = line.strip() 
 if line.startswith(">"): 
     index += 1 
     descriptions.append(line[1:])  # Remove the '>' at the beginning. 
     sequences.append("") 
     continue 
 elif line.startswith("#"):
     continue
 elif not line: 
     continue  # Skip blank lines. 
 sequences[index] += line 
```

**Comment by gahdritz** [comment]
Fixed in ddd1d79.

P.S. For the detail, formatting, and pre-emptive bugfixing, this gets the award for the best OpenFold issue so far lol --- thanks for taking the time to put this together!
