### ISSUE TITLE
Unexpected key(s) in state_dict error for model_3 inference

### ISSUE THREAD

**Issue by epenning** [aqlaboratory/openfold#156]
### Expected behavior:

I can run inference with `model_3` using OpenFold's `finetuning_3.pt`.

### Actual behavior:

In a local installation, this error happens before the inference begins:

```python
Traceback (most recent call last):
  File "run_pretrained_openfold.py", line 499, in <module>
    main(args)
  File "run_pretrained_openfold.py", line 359, in main
    for model, output_directory in load_models_from_command_line(args, config):
  File "run_pretrained_openfold.py", line 283, in load_models_from_command_line
    model.load_state_dict(d)
  File "<...>/miniconda3/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for AlphaFold:
	Unexpected key(s) in state_dict: "template_angle_embedder.linear_1.weight", "template_angle_embedder.linear_1.bias", "template_angle_embedder.linear_2.weight", "template_angle_embedder.linear_2.bias", "template_pair_embedder.linear.weight", "template_pair_embedder.linear.bias", "template_pair_stack.blocks.0.tri_att_start.layer_norm.weight", "template_pair_stack.blocks.0.tri_att_start.layer_norm.bias", "template_pair_stack.blocks.0.tri_att_start.linear.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_q.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_k.weight", "template_pair_stack.blocks.0.tri_at ... (truncated for length)
```

<details>
    <summary>Full output</summary>
<code>INFO:run_pretrained_openfold.py:Using precomputed alignments at <...>/msa_input...</code></br>  
<code>Traceback (most recent call last):</code></br>  
<code>  File "run_pretrained_openfold.py", line 499, in <module></code></br>  
<code>    main(args)</code></br>  
<code>  File "run_pretrained_openfold.py", line 359, in main</code></br>  
<code>    for model, output_directory in load_models_from_command_line(args, config):</code></br>  
<code>  File "run_pretrained_openfold.py", line 283, in load_models_from_command_line</code></br>  
<code>    model.load_state_dict(d)</code></br>  
<code>  File "<...>/miniconda3/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict</code></br>  
<code>    self.__class__.__name__, "\n\t".join(error_msgs)))</code></br>  
<code>RuntimeError: Error(s) in loading state_dict for AlphaFold:</code></br>  
<code>	Unexpected key(s) in state_dict: "template_angle_embedder.linear_1.weight", "template_angle_embedder.linear_1.bias", "template_angle_embedder.linear_2.weight", "template_angle_embedder.linear_2.bias", "template_pair_embedder.linear.weight", "template_pair_embedder.linear.bias", "template_pair_stack.blocks.0.tri_att_start.layer_norm.weight", "template_pair_stack.blocks.0.tri_att_start.layer_norm.bias", "template_pair_stack.blocks.0.tri_att_start.linear.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_q.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_k.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_v.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_o.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_o.bias", "template_pair_stack.blocks.0.tri_att_start.mha.linear_g.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_g.bias", "template_pair_stack.blocks.0.tri_att_end.layer_norm.weight", "template_pair_stack.blocks.0.tri_att_end.layer_norm.bias", "template_pair_stack.blocks.0.tri_att_end.linear.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_q.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_k.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_v.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_o.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_o.bias", "template_pair_stack.blocks.0.tri_att_end.mha.linear_g.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_g.bias", "template_pair_stack.blocks.0.tri_mul_out.linear_a_p.weight", "template_pair_stack.blocks.0.tri_mul_out.linear_a_p.bias", "template_pair_stack.blocks.0.tri_mul_out.linear_a_g.weight", "template_pair_stack.blocks.0.tri_mul_out.linear_a_g.bias", "template_pair_stack.blocks.0.tri_mul_out.linear_b_p.weight", "template_pair_stack.blocks.0.tri_mul_out.linear_b_p.bias", "template_pair_stack.blocks.0.tri_mul_out.linear_b_g.weight", "template_pair_stack.blocks.0.tri_mul_out.linear_b_g.bias", "template_pair_stack.blocks.0.tri_mul_out.linear_g.weight", "template_pair_stack.blocks.0.tri_mul_out.linear_g.bias", "template_pair_stack.blocks.0.tri_mul_out.linear_z.weight", "template_pair_stack.blocks.0.tri_mul_out.linear_z.bias", "template_pair_stack.blocks.0.tri_mul_out.layer_norm_in.weight", "template_pair_stack.blocks.0.tri_mul_out.layer_norm_in.bias", "template_pair_stack.blocks.0.tri_mul_out.layer_norm_out.weight", "template_pair_stack.blocks.0.tri_mul_out.layer_norm_out.bias", "template_pair_stack.blocks.0.tri_mul_in.linear_a_p.weight", "template_pair_stack.blocks.0.tri_mul_in.linear_a_p.bias", "template_pair_stack.blocks.0.tri_mul_in.linear_a_g.weight", "template_pair_stack.blocks.0.tri_mul_in.linear_a_g.bias", "template_pair_stack.blocks.0.tri_mul_in.linear_b_p.weight", "template_pair_stack.blocks.0.tri_mul_in.linear_b_p.bias", "template_pair_stack.blocks.0.tri_mul_in.linear_b_g.weight", "template_pair_stack.blocks.0.tri_mul_in.linear_b_g.bias", "template_pair_stack.blocks.0.tri_mul_in.linear_g.weight", "template_pair_stack.blocks.0.tri_mul_in.linear_g.bias", "template_pair_stack.blocks.0.tri_mul_in.linear_z.weight", "template_pair_stack.blocks.0.tri_mul_in.linear_z.bias", "template_pair_stack.blocks.0.tri_mul_in.layer_norm_in.weight", "template_pair_stack.blocks.0.tri_mul_in.layer_norm_in.bias", "template_pair_stack.blocks.0.tri_mul_in.layer_norm_out.weight", "template_pair_stack.blocks.0.tri_mul_in.layer_norm_out.bias", "template_pair_stack.blocks.0.pair_transition.layer_norm.weight", "template_pair_stack.blocks.0.pair_transition.layer_norm.bias", "template_pair_stack.blocks.0.pair_transition.linear_1.weight", "template_pair_stack.blocks.0.pair_transition.linear_1.bias", "template_pair_stack.blocks.0.pair_transition.linear_2.weight", "template_pair_stack.blocks.0.pair_transition.linear_2.bias", "template_pair_stack.blocks.1.tri_att_start.layer_norm.weight", "template_pair_stack.blocks.1.tri_att_start.layer_norm.bias", "template_pair_stack.blocks.1.tri_att_start.linear.weight", "template_pair_stack.blocks.1.tri_att_start.mha.linear_q.weight", "template_pair_stack.blocks.1.tri_att_start.mha.linear_k.weight", "template_pair_stack.blocks.1.tri_att_start.mha.linear_v.weight", "template_pair_stack.blocks.1.tri_att_start.mha.linear_o.weight", "template_pair_stack.blocks.1.tri_att_start.mha.linear_o.bias", "template_pair_stack.blocks.1.tri_att_start.mha.linear_g.weight", "template_pair_stack.blocks.1.tri_att_start.mha.linear_g.bias", "template_pair_stack.blocks.1.tri_att_end.layer_norm.weight", "template_pair_stack.blocks.1.tri_att_end.layer_norm.bias", "template_pair_stack.blocks.1.tri_att_end.linear.weight", "template_pair_stack.blocks.1.tri_att_end.mha.linear_q.weight", "template_pair_stack.blocks.1.tri_att_end.mha.linear_k.weight", "template_pair_stack.blocks.1.tri_att_end.mha.linear_v.weight", "template_pair_stack.blocks.1.tri_att_end.mha.linear_o.weight", "template_pair_stack.blocks.1.tri_att_end.mha.linear_o.bias", "template_pair_stack.blocks.1.tri_att_end.mha.linear_g.weight", "template_pair_stack.blocks.1.tri_att_end.mha.linear_g.bias", "template_pair_stack.blocks.1.tri_mul_out.linear_a_p.weight", "template_pair_stack.blocks.1.tri_mul_out.linear_a_p.bias", "template_pair_stack.blocks.1.tri_mul_out.linear_a_g.weight", "template_pair_stack.blocks.1.tri_mul_out.linear_a_g.bias", "template_pair_stack.blocks.1.tri_mul_out.linear_b_p.weight", "template_pair_stack.blocks.1.tri_mul_out.linear_b_p.bias", "template_pair_stack.blocks.1.tri_mul_out.linear_b_g.weight", "template_pair_stack.blocks.1.tri_mul_out.linear_b_g.bias", "template_pair_stack.blocks.1.tri_mul_out.linear_g.weight", "template_pair_stack.blocks.1.tri_mul_out.linear_g.bias", "template_pair_stack.blocks.1.tri_mul_out.linear_z.weight", "template_pair_stack.blocks.1.tri_mul_out.linear_z.bias", "template_pair_stack.blocks.1.tri_mul_out.layer_norm_in.weight", "template_pair_stack.blocks.1.tri_mul_out.layer_norm_in.bias", "template_pair_stack.blocks.1.tri_mul_out.layer_norm_out.weight", "template_pair_stack.blocks.1.tri_mul_out.layer_norm_out.bias", "template_pair_stack.blocks.1.tri_mul_in.linear_a_p.weight", "template_pair_stack.blocks.1.tri_mul_in.linear_a_p.bias", "template_pair_stack.blocks.1.tri_mul_in.linear_a_g.weight", "template_pair_stack.blocks.1.tri_mul_in.linear_a_g.bias", "template_pair_stack.blocks.1.tri_mul_in.linear_b_p.weight", "template_pair_stack.blocks.1.tri_mul_in.linear_b_p.bias", "template_pair_stack.blocks.1.tri_mul_in.linear_b_g.weight", "template_pair_stack.blocks.1.tri_mul_in.linear_b_g.bias", "template_pair_stack.blocks.1.tri_mul_in.linear_g.weight", "template_pair_stack.blocks.1.tri_mul_in.linear_g.bias", "template_pair_stack.blocks.1.tri_mul_in.linear_z.weight", "template_pair_stack.blocks.1.tri_mul_in.linear_z.bias", "template_pair_stack.blocks.1.tri_mul_in.layer_norm_in.weight", "template_pair_stack.blocks.1.tri_mul_in.layer_norm_in.bias", "template_pair_stack.blocks.1.tri_mul_in.layer_norm_out.weight", "template_pair_stack.blocks.1.tri_mul_in.layer_norm_out.bias", "template_pair_stack.blocks.1.pair_transition.layer_norm.weight", "template_pair_stack.blocks.1.pair_transition.layer_norm.bias", "template_pair_stack.blocks.1.pair_transition.linear_1.weight", "template_pair_stack.blocks.1.pair_transition.linear_1.bias", "template_pair_stack.blocks.1.pair_transition.linear_2.weight", "template_pair_stack.blocks.1.pair_transition.linear_2.bias", "template_pair_stack.layer_norm.weight", "template_pair_stack.layer_norm.bias", "template_pointwise_att.mha.linear_q.weight", "template_pointwise_att.mha.linear_k.weight", "template_pointwise_att.mha.linear_v.weight", "template_pointwise_att.mha.linear_o.weight", "template_pointwise_att.mha.linear_o.bias".</code>
</details>

This also seems to happen in the Colab for `model_3` with the default placeholders, blocking progress to the output zip download. The error happened at the `model_3` stage of the section **Run OpenFold and download prediction**, with this output:

`Running model_3: 29% 2/7 [elapsed: 00:38 remaining: 01:24]`
```python
/opt/conda/lib/python3.7/site-packages/openfold/data/feature_pipeline.py:45: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  k: torch.tensor(v) for k, v in np_example.items() if k in features

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-11-28899244d813>](https://localhost:8080/#) in <module>()
     52       )
     53       d = torch.load(params_name)
---> 54       openfold_model.load_state_dict(d)
     55     else:
     56       raise ValueError(f"Invalid weight set: {weight_set}")

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict)
   1603         if len(error_msgs) > 0:
   1604             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
-> 1605                                self.__class__.__name__, "\n\t".join(error_msgs)))
   1606         return _IncompatibleKeys(missing_keys, unexpected_keys)
   1607 

RuntimeError: Error(s) in loading state_dict for AlphaFold:
	Unexpected key(s) in state_dict: "template_angle_embedder.linear_1.weight", "template_angle_embedder.linear_1.bias", "template_angle_embedder.linear_2.weight", "template_angle_embedder.linear_2.bias", "template_pair_embedder.linear.weight", "template_pair_embedder.linear.bias", "template_pair_stack.blocks.0.tri_att_start.layer_norm.weight", "template_pair_stack.blocks.0.tri_att_start.layer_norm.bias", "template_pair_stack.blocks.0.tri_att_start.linear.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_q.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_k.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_v.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_o.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_o.bias", "template_pair_stack.blocks.0.tri_att_start.mha.linear_g.weight", "template_pair_stack.blocks.0.tri_att_start.mha.linear_g.bias", "template_pair_stack.blocks.0.tri_att_end.layer_norm.weight", "template_pair_stack.blocks.0.tri_att_end.layer_norm.bias", "template_pair_stack.blocks.0.tri_att_end.linear.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_q.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_k.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_v.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_o.weight", "template_pair_stack.blocks.0.tri_att_end.mha.linear_o.bias", "template_pair_stack.blocks.0.tri_att_end.mha.linear_g.weight", "template_p...
```

### Context

These are my inputs and command for running locally. I also used the precomputed MSA from the output of previous alignment for the same sequence just for speed, but this issue still seems to happen without using precomputed MSA based on the Colab error.

`input/short.fasta`
```
>query
MAAHKGAEHHHKAAEHHEQAAKHHHAAAEHHEKGEHEQAAHHADTAYAHHKHAEEHAAQAAKHDAEHHAPKPH
```

Command to run:
```bash
python3 run_pretrained_openfold.py \
    $input_dir \
    data/pdb_mmcif/mmcif_files/ \
    --output_dir $output_dir \
    --cpus 16 \
    --preset reduced_dbs \
    --use_precomputed_alignments $msa_input_dir \
    --uniref90_database_path data/uniref90/uniref90.fasta \
    --mgnify_database_path data/mgnify/mgy_clusters_2018_12.fa \
    --pdb70_database_path data/pdb70/pdb70 \
    --uniclust30_database_path data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --bfd_database_path data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --model_device "cuda:0" \
    --jackhmmer_binary_path $venv_bin_dir/jackhmmer \
    --hhblits_binary_path $venv_bin_dir/hhblits \
    --hhsearch_binary_path $venv_bin_dir/hhsearch \
    --kalign_binary_path $venv_bin_dir/kalign \
    --config_preset "model_3" \
    --openfold_checkpoint_path openfold/resources/openfold_params/finetuning_3.pt
```

**Comment by gahdritz** [comment]
This is expected. The `model_3` config preset, which disables templates, is incompatible with `finetuning_3`, which has template parameters. We trained OpenFold using the abbreviated training schedule in Table 4 of the AlphaFold2 supplement, so our `finetuning_i` models don't track exactly with AlphaFold's `model_i` models. To improve the diversity of OpenFold's parameter sets, we've trained a second, independent finetuning branch without templates (should be uploaded this week), which will be compatible with `model_{3-5}`.
