### ISSUE TITLE
Compiling 'CUDA' kernels

### ISSUE THREAD

**Issue by MrDotOne** [aqlaboratory/openfold#157]
Trying to run this script to compile the cuda kernels "(openfold_venv) # python3 setup.py install" and i get this error. Conda python is 3.7 so why is this complaining about needing 3.8?

  File "/cm/shared/apps/openfold/1.0.0/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-0q__qz6k/scipy-1.9.0rc2/setup.py", line 33, in <module>
    '--expt-relaxed-constexpr',
RuntimeError: Python version >= 3.8 required.
(openfold_venv) [root@cc-dclrilog61 1.0.0]# python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
(openfold_venv) [root@cc-dclrilog61 1.0.0]#

**Comment by gahdritz** [comment]
I am unable to reproduce this. Did you set up your virtualenv using the OpenFold installation scripts?

**Comment by MrDotOne** [comment]
I did use the install script and updated the version of conda.

**Comment by gahdritz** [comment]
Looks good. I'll mark this as resolved for now.
