### ISSUE TITLE
Unusual predicted structures from pretrained OpenFold on Pascal GPU

### ISSUE THREAD

**Issue by epenning** [aqlaboratory/openfold#161]
This is most likely some kind of local configuration error, but I haven't been able to pin down the cause. If anyone has encountered this behavior before or has an idea of what might be wrong based on these output structures, any hints would be greatly appreciated!

### Expected behavior:

`run_pretrained_openfold.py` outputs predicted structures comparable to AlphaFold or OpenFold Colab output.

I expected a structure similar to this unrelaxed prediction from OpenFold Colab `model_1` with `finetuning_1.pt`:  
<img width="368" alt="image" src="https://user-images.githubusercontent.com/8647254/179286410-5d27d1c1-8aa7-4941-9139-999917ab5fe3.png">

### Actual behavior:

My `run_pretrained_openfold.py` predicted structures are not similar to AlphaFold or OpenFold Colab output.

Predictions from `model_1` with `finetuning_1.pt` (unrelaxed in tan, relaxed in blue):  
<img width="199" alt="image" src="https://user-images.githubusercontent.com/8647254/179286457-e0e10d63-1a69-4b0a-892f-ec0fea2110b7.png">

Predictions from `model_1` with `params_model_1.npz`:  
<img width="210" alt="image" src="https://user-images.githubusercontent.com/8647254/179286501-989bf098-1473-45c4-b26e-a9f65dbc1bf2.png">

Predictions from `model_1` with `params_model_1.npz` using alignments from ColabFold MMseqs2 (ColabFold had predicted a reasonable expected structure):  
<img width="357" alt="image" src="https://user-images.githubusercontent.com/8647254/179286542-16dc5d97-d181-4785-835b-3382153f83c3.png">

### Context:

4 x NVidia 1080-TI GPUs
Using CUDA 11.3
(if other system data is relevant I can find it)

`input/short.fasta`
```
>query
MAAHKGAEHHHKAAEHHEQAAKHHHAAAEHHEKGEHEQAAHHADTAYAHHKHAEEHAAQAAKHDAEHHAPKPH
```

Run command:
```bash
python3 run_pretrained_openfold.py \
    input \
    data/pdb_mmcif/mmcif_files/ \
    --output_dir output \
    --cpus 16 \
    --preset reduced_dbs \
    --uniref90_database_path data/uniref90/uniref90.fasta \
    --mgnify_database_path data/mgnify/mgy_clusters_2018_12.fa \
    --pdb70_database_path data/pdb70/pdb70 \
    --uniclust30_database_path data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --bfd_database_path data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --model_device "cuda:0" \
    --jackhmmer_binary_path $venv_bin_dir/jackhmmer \
    --hhblits_binary_path $venv_bin_dir/hhblits \
    --hhsearch_binary_path $venv_bin_dir/hhsearch \
    --kalign_binary_path $venv_bin_dir/kalign \
    --config_preset "model_1" \
    --openfold_checkpoint_path openfold/resources/openfold_params/finetuning_1.pt
```

Other configurations I tried, which produced similarly strange outputs:
* Removing `--openfold_checkpoint_path` to just use the AlphaFold weights
* Using `--config_preset "model_1_ptm"` with `finetuning_ptm_2.pt`
* Using `--use_precomputed_alignments` with alignment results from a previous OpenFold output
* Using `--use_precomputed_alignments` with `.a3m` results from ColabFold
* Using `full_dbs` instead of `reduced_dbs`

**Comment by gahdritz** [comment]
Could you verify the git commit hash of your installation + that the git diff shows no modifications to the model code?

**Comment by gahdritz** [comment]
Could you try disabling the custom CUDA kernels on the bad system? Specifically, make sure that all occurrences of `use_memory_efficient_kernel` and `use_flash` are set to `False` in the config.

**Comment by epenning** [comment]
Since this is happening on the release tag `v1.0.0`, `use_flash` isn't present there yet.

Where in the config should I set `use_memory_efficient_kernel`, since it's not assigned there already?

**Comment by gahdritz** [comment]
Ah my bad I never added it to the config. You'll have to disable `use_memory_efficient_kernel` manually in `openfold/model/evoformer.py`. There should only be one occurrence of it there; change the setting from `not use_lma` to `False`.

**Comment by epenning** [comment]
Thanks! I changed that line from `not use_lma` to `False` and ran it again, but it still produced another bad prediction.

**Comment by epenning** [comment]
I tried a couple different re-installations on the 1080 system, here's an update on that:

* I fully removed OF from the 1080 system and installed it from scratch, although again the predictions were still bad.
* From the system that did work, I installed OF on the shared filesystem. When running that installation from the working system, I did get good predictions, but running the same installation (with the same parameters and inputs) from the 1080 system still produced bad structures.

Since then I also created an additional installation in the shared filesystem, for a newer commit than v1.0.0 (236c68650a2ffbd846e51498d8b719c2b834ca38). This installation works on the good system (Quadro RTX 5000), but instead of bad output on the 1080 system, it encounters an error: `RuntimeError: CUDA error: no kernel image is available for execution on the device` I'm not sure what the cause is, or if it's relevant or not to the bad structure predictions on v1.0.0.

<details>
<summary>Here's the full stack trace from the error that happened on the 1080 system for the newer installation.</summary>

```
INFO:/.../shared/openfold/run_pretrained_openfold.py:Loaded OpenFold parameters at /.../shared/openfold/openfold/resources/openfold_params/finetuning_ptm_2.pt...
INFO:/.../shared/openfold/run_pretrained_openfold.py:Using precomputed alignments for query at /.../msa_input...
INFO:/.../shared/openfold/run_pretrained_openfold.py:Running inference for query...
Traceback (most recent call last):
  File "/.../shared/openfold/run_pretrained_openfold.py", line 591, in <module>
    main(args)
  File "/.../shared/openfold/run_pretrained_openfold.py", line 439, in main
    out = run_model(model, processed_feature_dict, tag, args)
  File "/.../shared/openfold/run_pretrained_openfold.py", line 119, in run_model
    out = model(batch)
  File "/.../shared/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/.../shared/openfold/openfold/model/model.py", line 510, in forward
    _recycle=(num_iters > 1)
  File "/.../shared/openfold/openfold/model/model.py", line 367, in iteration
    _mask_trans=self.config._mask_trans,
  File "/.../shared/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/.../shared/openfold/openfold/model/evoformer.py", line 998, in forward
    m, z = b(m, z)
  File "/.../shared/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/.../shared/openfold/openfold/model/evoformer.py", line 519, in forward
    self.ckpt if torch.is_grad_enabled() else False,
  File "/.../shared/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/.../shared/openfold/openfold/model/msa.py", line 273, in forward
    flash_mask=mask,
  File "/.../shared/openfold/openfold/model/msa.py", line 125, in _chunk
    no_batch_dims=len(m.shape[:-2])
  File "/.../shared/openfold/openfold/utils/chunk_utils.py", line 299, in chunk_layer
    output_chunk = layer(**chunks)
  File "/.../shared/openfold/openfold/model/msa.py", line 108, in fn
    flash_mask=flash_mask,
  File "/.../shared/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/.../shared/openfold/openfold/model/primitives.py", line 488, in forward
    o = attention_core(q, k, v, *((biases + [None] * 2)[:2]))
  File "/.../shared/openfold/openfold/utils/kernel/attention_core.py", line 53, in forward
    o = torch.matmul(attention_logits, v) 
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
</details>

Since I do have access to a system that is working, this isn't a high priority for me, but I figured this extra information could be useful in the future. There might just be something subtly wrong with the environment in the 1080 system that I wasn't able to identify.

**Comment by gahdritz** [comment]
Thanks for the diagnostics. This isn't the only Pascal GPU that's given OpenFold trouble, so it looks to me like the issue isn't just with your setup in particular. Since I can't reproduce this ATM, I'll let this sit, but I'll leave it open in case the problem resurfaces somewhere.

**Comment by epenning** [comment]
I've confirmed that this was resolved with the fix for https://github.com/aqlaboratory/openfold/issues/172! 👏
