### ISSUE TITLE
Fails to run a prediction even on an example sequence

### ISSUE THREAD

**Issue by kkorotkov27** [aqlaboratory/openfold#162]
I've tried to run this notebook a few times, and it crushes every time, even with an example sequence. Any insight?

**Comment by gahdritz** [comment]
I'll need some more information. How does it crash?

**Comment by kkorotkov27** [comment]
Hello,

'Run OpenFold...' cell gives this error:
File "<ipython-input-6-ac125295258f>" <https://localhost:8080/#>, line
43 if(weight_set
== "AlphaFold") ^ SyntaxError: invalid syntax

**Comment by gahdritz** [comment]
This should be fixed now. LMK if you run into any more issues running it.

**Comment by kkorotkov27** [comment]
Thanks!

No I've gotten the following:

Running finetuning_2.pt: 0%
0/6 [elapsed: 00:11 remaining: ?]

/opt/conda/lib/python3.7/site-packages/openfold/data/feature_pipeline.py:45:
UserWarning: To copy construct from a tensor, it is recommended to use
sourceTensor.clone().detach() or
sourceTensor.clone().detach().requires_grad_(True), rather than
torch.tensor(sourceTensor).
  k: torch.tensor(v) for k, v in np_example.items() if k in features

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-7-3b0e81c4d0e7> <https://localhost:8080/#> in
<module>()     78      79     with torch.no_grad():
---> 80       prediction_result =
openfold_model(processed_feature_dict)     81      82     # Move the
batch and output to np for further processing


------------------------------
14 frames
------------------------------

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py
<https://localhost:8080/#> in _call_impl(self, *input, **kwargs)
1128         if not (self._backward_hooks or self._forward_hooks or
self._forward_pre_hooks or _global_backward_hooks   1129
  or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)   1131
  # Do not call functions when jit is used   1132
full_backward_hooks, non_full_backward_hooks = [], []


/opt/conda/lib/python3.7/site-packages/openfold/model/model.py
<https://localhost:8080/#> in forward(self, batch)    508
       feats,    509                     prevs,
--> 510                     _recycle=(num_iters > 1)    511
     )    512

/opt/conda/lib/python3.7/site-packages/openfold/model/model.py
<https://localhost:8080/#> in iteration(self, feats, prevs, _recycle)
  365                     pair_mask=pair_mask.to(dtype=m.dtype),
366                     inplace_safe=inplace_safe,
--> 367                     _mask_trans=self.config._mask_trans,
368                 )    369

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py
<https://localhost:8080/#> in _call_impl(self, *input, **kwargs)
1128         if not (self._backward_hooks or self._forward_hooks or
self._forward_pre_hooks or _global_backward_hooks   1129
  or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)   1131
  # Do not call functions when jit is used   1132
full_backward_hooks, non_full_backward_hooks = [], []


/opt/conda/lib/python3.7/site-packages/openfold/model/evoformer.py
<https://localhost:8080/#> in forward(self, m, z, msa_mask, pair_mask,
chunk_size, use_lma, inplace_safe, _mask_trans)    996
m, z = checkpoint_fn(b, m, z)    997             else:
--> 998                 m, z = b(m, z)    999    1000         return z


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py
<https://localhost:8080/#> in _call_impl(self, *input, **kwargs)
1128         if not (self._backward_hooks or self._forward_hooks or
self._forward_pre_hooks or _global_backward_hooks   1129
  or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)   1131
  # Do not call functions when jit is used   1132
full_backward_hooks, non_full_backward_hooks = [], []


/opt/conda/lib/python3.7/site-packages/openfold/model/evoformer.py
<https://localhost:8080/#> in forward(self, m, z, msa_mask, pair_mask,
chunk_size, use_lma, inplace_safe, _mask_trans, _attn_chunk_size,
_offload_inference, _offloadable_inputs)    517
use_memory_efficient_kernel=not use_lma,    518
_checkpoint_chunks=
--> 519                         self.ckpt if torch.is_grad_enabled()
else False,    520                 )    521             ),


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py
<https://localhost:8080/#> in _call_impl(self, *input, **kwargs)
1128         if not (self._backward_hooks or self._forward_hooks or
self._forward_pre_hooks or _global_backward_hooks   1129
  or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)   1131
  # Do not call functions when jit is used   1132
full_backward_hooks, non_full_backward_hooks = [], []


/opt/conda/lib/python3.7/site-packages/openfold/model/msa.py
<https://localhost:8080/#> in forward(self, m, z, mask, chunk_size,
use_memory_efficient_kernel, use_lma, use_flash, inplace_safe,
_chunk_logits, _checkpoint_chunks)    271
use_lma=use_lma,    272                 use_flash=use_flash,
--> 273                 flash_mask=mask,    274             )    275
      else:


/opt/conda/lib/python3.7/site-packages/openfold/model/msa.py
<https://localhost:8080/#> in _chunk(self, m, biases, chunk_size,
use_memory_efficient_kernel, use_lma, use_flash, flash_mask)    123
         inputs,    124             chunk_size=chunk_size,
--> 125             no_batch_dims=len(m.shape[:-2])    126         )    127

/opt/conda/lib/python3.7/site-packages/openfold/utils/chunk_utils.py
<https://localhost:8080/#> in chunk_layer(layer, inputs, chunk_size,
no_batch_dims, low_mem, _out, _add_into_out)    297     298         #
Run the layer on the chunk
--> 299         output_chunk = layer(**chunks)    300     301
# Allocate space for the output


/opt/conda/lib/python3.7/site-packages/openfold/model/msa.py
<https://localhost:8080/#> in fn(m, biases, flash_mask)    106
        use_lma=use_lma,    107                 use_flash=use_flash,
--> 108                 flash_mask=flash_mask,    109             )    110

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py
<https://localhost:8080/#> in _call_impl(self, *input, **kwargs)
1128         if not (self._backward_hooks or self._forward_hooks or
self._forward_pre_hooks or _global_backward_hooks   1129
  or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)   1131
  # Do not call functions when jit is used   1132
full_backward_hooks, non_full_backward_hooks = [], []


/opt/conda/lib/python3.7/site-packages/openfold/model/primitives.py
<https://localhost:8080/#> in forward(self, q_x, kv_x, biases,
use_memory_efficient_kernel, use_lma, lma_q_chunk_size,
lma_kv_chunk_size, use_flash, flash_mask)    476
"provide up to two bias terms"    477                 )
--> 478             o = attention_core(q, k, v, *((biases + [None] *
2)[:2]))    479             o = o.transpose(-2, -3)    480
elif(use_lma):


/opt/conda/lib/python3.7/site-packages/openfold/utils/kernel/attention_core.py
<https://localhost:8080/#> in forward(ctx, q, k, v, bias_1, bias_2)
 51         )     52
---> 53         o = torch.matmul(attention_logits, v)     54      55
      ctx.bias_1_shape = bias_1.shape if bias_1 is not None else None


RuntimeError: CUDA error: no kernel image is available for execution
on the device
CUDA kernel errors might be asynchronously reported at some other API
call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
