### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'. error while running Inference 

### ISSUE THREAD

**Issue by calmasri** [aqlaboratory/openfold#173]
Hello, 

I've been trying to run inference on sequences, but I'm getting the following error:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/107719001/180281110-26b64095-5d5b-460e-822b-1839d18f32f6.png">

Any idea what the issue might be? I downloaded all the required databases and didn't notice any errors or incomplete downloads.

Thanks!

**Comment by calmasri** [comment]
I noticed that my checkpoint files in /openfold/resources/openfold_params are all roughly 134 B. Could it be that they're somehow corrupt?

**Comment by gahdritz** [comment]
When did you download the params? What version of torch are you using?

**Comment by gahdritz** [comment]
Ignore the previous comment---I just remembered this happening to me a while ago. You need to install `git-lfs` before cloning the OF parameter repo.

P.S. - we've since released an updated parameter set hosted on RODA instead of HuggingFace. Check out `scripts/download_openfold_params.sh`.

**Comment by calmasri** [comment]
It worked, thanks!
