### ISSUE TITLE
mmcif_dir vs. template_mmcif_dir

### ISSUE THREAD

**Issue by lzhangUT** [aqlaboratory/openfold#174]
Hi
I am a little bit confused about the two directories in the command:
python3 train_openfold.py mmcif_dir/ alignment_dir/ template_mmcif_dir/ \
    2021-10-10 \ 
    --template_release_dates_cache_path mmcif_cache.json \ 
    --precision 16 \
    --gpus 8 --replace_sampler_ddp=True \
    --seed 42 \ # in multi-gpu settings, the seed must be specified
    --deepspeed_config_path deepspeed_config.json \
    --checkpoint_every_epoch \
    --resume_from_ckpt ckpt_dir/ \
    --train_chain_data_cache_path chain_data_cache.json \
    --obsolete_pdbs_file_path obsolete.dat

in our databases downloaded, there are only two pdb direcoties: mmcif_dir which contains ~190000 cif files, and the other one pdb70 which containes 9 files including .ffindex and .ffdata files). so in this command, I am not sure what tmplate_mmcif_dir is?
should it be always the same as mmcif_dir? or template_mmcif_dir is some directory created during the precomputed_alignment.py?

any help will be greatly appreciated

**Comment by gahdritz** [comment]
Using the standard configuration/RODA data, yes, it should be the same as `mmcif_dir`. I just separated it from `mmcif_dir` because, in principle, there's no reason why the prediction targets should have to be the same as the pool of potential templates.
