### ISSUE TITLE
Report bug that check if  deepspeed is_initialized  

### ISSUE THREAD

**Issue by pengzhangzhi** [aqlaboratory/openfold#176]
https://github.com/aqlaboratory/openfold/blob/0d2dd5d03b91d326a20ba27b91161efda201264e/openfold/model/primitives.py#L198

the latest version ([v0.6.7](https://github.com/microsoft/DeepSpeed/releases/tag/v0.6.7)) of deepspeed does not support check `is_initialized` in this way.

The correct way is  :
```
from deepspeed import comm as dist
dist.is_initialized()

```

**Comment by pengzhangzhi** [comment]
BTW, I am wondering why you want to do such check on layer norm? Is it because that you want the layer norm to be half precision when the input is half precision?

**Comment by gahdritz** [comment]
OpenFold depends on deepspeed v0.5.9, which does still support that function (the new one doesn't exist in the old version, unfortunately). That check is there to work around an AMP bug that may or may not exist anymore---previously, not doing this would balloon memory utilization.
