### ISSUE TITLE
UnboundLocalError: local variable 'generator' referenced before assignment

### ISSUE THREAD

**Issue by lzhangUT** [aqlaboratory/openfold#177]
Hi,
I ran successfully the precomputed_alignement_mmseqs.py, and then I ran generate_mmcif_cache.py, generate_chain_data_cache.py, which were successful as well, although it took a long time. then I ran the train_openfold.py following your script:

python3 train_openfold.py data/pdb_mmcif/mmcif_files/ alignment/ 
data/pdb_mmcif/mmcif_files/ output/ 2021-10-10 
--template_release_dates_cache_path mmcif_cache.json 
--precision 16 
--gpus 1 --replace_sampler_ddp=True 
--deepspeed_config_path deepspeed_config.json 
--checkpoint_every_epoch 
--resume_from_ckpt openfold/resources/openfold_params/ 
--train_chain_data_cache_path chain_data_cache.json 
--obsolete_pdbs_file_path data/pdb_mmcif/obsolete.dat

Traceback (most recent call last):
  File "train_openfold.py", line 558, in <module>
    main(args)
  File "train_openfold.py", line 270, in main
    data_module.setup()
  File "/datadrive/openfold/lib/conda/envs/openfold_venv/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/datadrive/openfold/openfold/data/data_modules.py", line 643, in setup
    generator=generator,
UnboundLocalError: local variable 'generator' referenced before assignment.

then I got this error, I am not sure what it is and what arguments caused that. My current VM only has one GPU, after testing openfold out, we are going to increase the GPUs. 
Can you help out to see what the error is, Thanks a LOT!

**Comment by gahdritz** [comment]
Fixed in `965961a`.
