### ISSUE TITLE
Option to run in "de-novo" mode

### ISSUE THREAD

**Issue by aiXander** [aqlaboratory/openfold#18]
Most of the scripts at `https://github.com/sokrypton/ColabFold` have a ton of additional flexibility that comes in handy when running AF on de-novo sequences (for which you usually can't generated an MSA) or to do protein-design with.

Can this codebase also be leveraged to:
- run predictions without MSA input or template structures, so just the raw sequence input
- increase the number of recycle iterations (since this has been shown to recover some of the accuracy lost by not having an MSA)

**Comment by gahdritz** [comment]
Yes to both.

1. Simply run the inference script using the --use_precomputed_alignments flag. Inference will be performed even if the alignments directory is empty.
2. The number of recycling iterations can be tuned in the model config, located at `openfold/config.py` under the "data" header.

**Comment by gahdritz** [comment]
Done! As of 61df432, you don't need any MSAs (or templates, for that matter) in the `alignment_dir` of either the inference or training scripts.
