### ISSUE TITLE
RuntimeError：expected scalar type Half but found BFloat16

### ISSUE THREAD

**Issue by zhangyuxuan1996** [aqlaboratory/openfold#180]
when I run train_openfold.py, I encountered the following error.
![C788D436-5AF3-4245-84E4-7CF0A8CA1144](https://user-images.githubusercontent.com/32118018/181805725-a8934704-c5d9-4239-8621-618da95e63fc.jpeg)

**Comment by gahdritz** [comment]
Could you send your training command?

**Comment by gahdritz** [comment]
@NZ99 could you also send your training command?

**Comment by NZ99** [comment]
Sure, my command is `srun python3 /fsx/openbioml/openfold/train_openfold.py /fsx/openbioml/openfold_data/pdb_mmcif/mmcif_files/ /fsx/openbioml/openfold_roda/pdb/ /fsx/openbioml/openfold_data/pdb_mmcif/mmcif_files /fsx/openbioml/openfold_out/ 2021-10-10 --template_release_dates_cache_path /fsx/openbioml/openfold_data/mmcif_cache.json --precision 16 --num_nodes 8 --gpus 8 --replace_sampler_ddp=True --seed 42 --deepspeed_config_path /fsx/openbioml/openfold/deepspeed_config.json --checkpoint_every_epoch --train_chain_data_cache_path /fsx/openbioml/openfold_data/chain_data_cache.json --obsolete_pdbs_file_path /fsx/openbioml/openfold_data/pdb_mmcif/obsolete.dat`. Running on a SLURM cluster with 8 nodes each with 8 A100s.

**Comment by gahdritz** [comment]
`--precision 16` tries to run the model in FP16 mode, which is unsupported. You need to use `--precision 32` or `--precision bf16`. In the latter case, you also need to make sure that bfloat16 is enabled in the DeepSpeed config. I should add a warning for `--precision 16`.

**Comment by NZ99** [comment]
Thank you! Looks like it's training fine now. I'm not sure how I made this mistake, I was sure I had copied it from the README...

Thank you again Gustaf! :)

**Comment by gahdritz** [comment]
(don't look too closely at ecd5a7e...)

**Comment by zhangyuxuan1996** [comment]
Thank you Gustaf！ --precision should be set as bf16 if we use the default deepspeed_config.json. The command raise 'RuntimeError：expected scalar type Half but found BFloat16' is as the same as Readme.md. 
By the way, there is missing output_dir input.
![image](https://user-images.githubusercontent.com/32118018/181863790-64bcb9b1-2d91-437d-a5a7-14fb203572ac.png)

**Comment by zhangyuxuan1996** [comment]
> Thank you Gustaf！I can run it by setting --precision as bf16. Previously, I use the default deepspeed_config.json, and the training launch command is same as Readme.md, which raise 'RuntimeError：expected scalar type Half but found BFloat16'. By the way, there is missing output_dir input in the readme.md. ![image](https://user-images.githubusercontent.com/32118018/181863790-64bcb9b1-2d91-437d-a5a7-14fb203572ac.png)

Awesome！I find the training sample command has been modified from 16->bf16

**Comment by gahdritz** [comment]
Fixed in d96f27b.
