### ISSUE TITLE
a simple bug report

### ISSUE THREAD

**Issue by Wangchentong** [aqlaboratory/openfold#183]
train_openfold.py has a bug makes fp16 precision get inf in model

`config = model_config(
        args.config_preset, 
        train=True, 
        low_prec=(args.precision == "16")
    ) `
precision here is parsed as int, so this equation will fail forever, please fix it.

**Comment by gahdritz** [comment]
Thanks! Fixed in 904de71. I'll add for the record that FP16 support is only semi-supported at the moment, to put it lightly. If at all possible, training in BF16 or full precision is recommended.
