### ISSUE TITLE
Self-distillation instructions

### ISSUE THREAD

**Issue by NZ99** [aqlaboratory/openfold#187]
Hello! I was wondering if you could provide further instructions regarding how to properly set-up self-distillation during training.

I have downloaded the data you've released over on [RODA](https://registry.opendata.aws/openfold/), and my understanding is that the `uniclust30/` directory is supposed to be used for self-distillation purposes. I guess I should move the `pdb` files therein in a separate directory which would become the `distillation_data_dir` (while the original alignments directory could do as the `distillation_alignment_dir`). Is this correct, or can I just leave them in the same directory (with the same directory structure)?

I also see that `train_openfold.py` also requires a `distillation_chain_data_cache_path` json file, which I guess should be generated using `scripts/generate_chain_data_cache.py`. I guess I should point it at the aforementioned `distillation_data_dir`, but what about the required `cluster_file`? What should I be using in this case?

As usual, thank you very much for this effort :)

**Comment by gahdritz** [comment]
Yes, this is all pretty much right. The `uniclust30` directory is indeed our distillation set. See the upcoming OF preprint or the AlphaFold supplement (whose procedure is approximately the same as what we did) for more details on how that was generated. 

Yes, you should move the `.pdb` files into a separate `distillation_data_dir`. The alignment files should be kept in directories named after the corresponding chain. All file format subdirectories should be flattened to make the OF dataloader happy; unless you're using the `alignment_index` data format, it expects directories corresponding to each chain containing only `.a3m` and `.hhr` files. More clearly, it expects:

```
distillation_alignment_dir/
---chain_name_1/
------uniclust30.a3m
------pdb70.hhr
---chain_name_2/
...
```


The AlphaFold paper is a little light on details on how the stochastic training-time filters apply to the self-distillation set. One reasonable interpretation is that the `cluster_file`-related filters don't apply to it. We read it that way, and so I generated the `distillation_chain_data_cache_path` with `cluster_file` set to `None`.

**Comment by NZ99** [comment]
FYI `generate_chain_data_cache.py` raises two errors when applying it to a directory with `.pdb` files. I'll open a pull request with a fix.
