### ISSUE TITLE
Get low lddt score while running inference.

### ISSUE THREAD

**Issue by WeixuanXiong** [aqlaboratory/openfold#189]
Excellent work!

I'm trying to run inference process of openfold.
My input fasta is :
>HBA_HUMAN
MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR

My shell command is:\
python3 run_pretrained_openfold.py \
>     data/fasta_dir \
>     data/pdb_mmcif/mmcif_files/ \
>     --uniref90_database_path data/uniref90/uniref90.fasta \
>     --mgnify_database_path data/mgnify/mgy_clusters_2018_12.fa \
>     --pdb70_database_path data/pdb70/pdb70 \
>     --uniclust30_database_path data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
>     --output_dir output/ \
>     --bfd_database_path data/small_bfd/bfd-first_non_consensus_sequences.fasta \
>     --model_device "cuda:0" \
>     --jackhmmer_binary_path lib/conda/envs/openfold_venv/bin/jackhmmer \
>     --hhblits_binary_path lib/conda/envs/openfold_venv/bin/hhblits \
>     --hhsearch_binary_path lib/conda/envs/openfold_venv/bin/hhsearch \
>     --kalign_binary_path lib/conda/envs/openfold_venv/bin/kalign \
>     --config_preset "finetuning_ptm" \
>     --openfold_checkpoint_path openfold/resources/openfold_params/finetuning_ptm_2.pt

And i got the following result:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/92519311/182341533-e1f91352-57d3-42ec-8451-24d76ddd9482.png">

The average of lddt is pretty low. And this situation happens every time even when i choose simple sequence.
Moreover, I notice that parameter 'use_small_bfd' is set to be false by default. But inference works when i set 'bfd_database_path' data/small_bfd/bfd-first_non_consensus_sequences.fasta.

I'm wondering what happened and hope for your reply.

**Comment by gahdritz** [comment]
You shouldn't use the "finetuning_ptm," which is a training config preset, for inference. Use "model_1_ptm" instead. 

Even if that's not the cause, there are many reasons why the confidence could be low, including that the MSAs are too shallow. I recommend using the full BFD for this protein and trying again, if possible.

**Comment by WeixuanXiong** [comment]
Changing command below:

python3 run_pretrained_openfold.py \
    data/fasta_dir \
    data/pdb_mmcif/mmcif_files/ \
    --uniref90_database_path data/uniref90/uniref90.fasta \
    --mgnify_database_path data/mgnify/mgy_clusters_2018_12.fa \
    --pdb70_database_path data/pdb70/pdb70 \
    --uniclust30_database_path data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --output_dir output/ \
    --bfd_database_path data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --model_device "cuda:0" \
    --jackhmmer_binary_path lib/conda/envs/openfold_venv/bin/jackhmmer \
    --hhblits_binary_path lib/conda/envs/openfold_venv/bin/hhblits \
    --hhsearch_binary_path lib/conda/envs/openfold_venv/bin/hhsearch \
    --kalign_binary_path lib/conda/envs/openfold_venv/bin/kalign \
    --config_preset "model_1_ptm" \ 
    --openfold_checkpoint_path openfold/resources/openfold_params/finetuning_ptm_2.pt

confidence is still pretty low:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/92519311/182508313-8e20edf6-d22e-4942-8c44-3961354a19a3.png">


I'm wondering if my inference setting is wrong because i can normally run inference command even when i haven't unzip bfd dataset.

**Comment by WeixuanXiong** [comment]
Since i change openfold params to jax params from alphafold, some of my test input are normally predicted. But this HBA_HUMAN is still bad.

**Comment by gahdritz** [comment]
AlphaFold isn't perfect, and some proteins aren't predicted with high confidence even when everything is working correctly. This is looking to me like such a case.

BTW - if you were running OF before with BFD zipped, OF must just not have been using BFD. Each of the alignment databases is optional.

**Comment by WeixuanXiong** [comment]
THX to your prompt reply, i'll give it another try with more different inputs.

**Comment by WeixuanXiong** [comment]
I‘ve made several attempt below:

>GRAB_HUMAN
MQPILLLLAFLLLPRADAGEIIGGHEAKPHSRPYMAYLMIWDQKSLKRCGGFLIRDDFVLTAAHCWGSSINVTLGAHNIKEQEPTQQFIPVKRPIPHPAYNPKNFSNDIMLLQLERKAKRTRAVQPLRLPSNKAQVKPGQTCSVAGWGQTAPLGKHSHTLQEVKMTVQEDRKCESDLRHYYDSTIELCVGDPEIKKTSFKGDSGGPLVCNKVAQGIVSYGRNNGMPPRACTKVSSFVHWIKKTMKRY

<img width="423" alt="image" src="https://user-images.githubusercontent.com/92519311/182565122-8dbe999d-1254-4622-a166-0afd3f37670b.png">

>RHEX_HUMAN
MLTEVMEVWHGLVIAVVSLFLQACFLTAINYLLSRHMAHKSEQILKAASLQVPRPSPGHHHPPAVKEMKETQTERDIPMSDSLYRHDSDTPSDSLDSSCSSPPACQATEDVDYTQVVFSDPGELKNDSPLDYENIKEITDYVNVNPERHKPSFWYFVNPALSEPAEYDQVAM

<img width="468" alt="image" src="https://user-images.githubusercontent.com/92519311/182565284-3021d023-a5e1-4cf5-9993-a487aabd746a.png">

>UniRef50_I7GMQ5
MIISIDTEKAFDKIKHCFMQKTLDKLGIDGNFLKIIELLTTNPQPHHTKLAKARKIPFENHHKTSMPSLTTPIQHSIESSSQGNHARERNKGYSNRKRGS
<img width="502" alt="image" src="https://user-images.githubusercontent.com/92519311/182565451-f4b4f41b-b317-4d64-80b5-2933e25e98ad.png">

>Q92956-1
MEPPGDWGPPPWRSTPKTDVLRLVLYLTFLGAPCYAPALPSCKEDEYPVGSECCPKCSPGYRVKEACGELTGTVCEPCPPGTYIAHLNGLSKCLQCQMCDPAMGLRASRNCSRTENAVCGCSPGHFCIVQDGDHCAACRAYATSSPGQRVQKGGTESQDTLCQNCPPGTFSPNGTLEECQHQTKCSWLVTKAGAGTSSSHWVWWFLSGSLVIVIVCSTVGLIICVKRRKPRGDVVKVIVSVQRKRQEAEGEATVIEALQAPPDVTTVAVEETIPSFTGRSPNH

<img width="464" alt="image" src="https://user-images.githubusercontent.com/92519311/182565637-308354cc-8890-4bea-8284-ce615c503c2a.png">

it seems that both jax params and OF params fail to properly predict those inputs while those inputs are from uniprot.
I'm wondering if there is any other problem in my inference settings.

**Comment by gahdritz** [comment]
Try running these through ColabFold or something; I suspect you'll get similar results.

**Comment by WeixuanXiong** [comment]
HBA_HUMAN
MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR

<img width="413" alt="image" src="https://user-images.githubusercontent.com/92519311/182746034-4e5f1883-ec20-41d1-8c42-0dd8ca8c1743.png">

GRAB_HUMAN
MQPILLLLAFLLLPRADAGEIIGGHEAKPHSRPYMAYLMIWDQKSLKRCGGFLIRDDFVLTAAHCWGSSINVTLGAHNIKEQEPTQQFIPVKRPIPHPAYNPKNFSNDIMLLQLERKAKRTRAVQPLRLPSNKAQVKPGQTCSVAGWGQTAPLGKHSHTLQEVKMTVQEDRKCESDLRHYYDSTIELCVGDPEIKKTSFKGDSGGPLVCNKVAQGIVSYGRNNGMPPRACTKVSSFVHWIKKTMKRY

<img width="478" alt="image" src="https://user-images.githubusercontent.com/92519311/182746078-7c28b0b3-e8bd-45cb-9fed-9c7ac073fdef.png">

RHEX_HUMAN
MLTEVMEVWHGLVIAVVSLFLQACFLTAINYLLSRHMAHKSEQILKAASLQVPRPSPGHHHPPAVKEMKETQTERDIPMSDSLYRHDSDTPSDSLDSSCSSPPACQATEDVDYTQVVFSDPGELKNDSPLDYENIKEITDYVNVNPERHKPSFWYFVNPALSEPAEYDQVAM

<img width="519" alt="image" src="https://user-images.githubusercontent.com/92519311/182748175-4663b38a-f789-4fa0-afc8-bbbfc9ed9667.png">

UniRef50_I7GMQ5
MIISIDTEKAFDKIKHCFMQKTLDKLGIDGNFLKIIELLTTNPQPHHTKLAKARKIPFENHHKTSMPSLTTPIQHSIESSSQGNHARERNKGYSNRKRGS
![Uploading image.png…]()

Here are the results from colabfold. It seems that some inputs are predicted as bad as OF did while some are not. Could you plz offer me some proteins which have been tested good by yourself or run my test input on your device to check if some other issues' occurrance.

**Comment by gahdritz** [comment]
Try the default protein in the OpenFold Colab. That one should work. Alternatively, try the sequence listed in issue #172.

**Comment by WeixuanXiong** [comment]
sequence from issue:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/92519311/182986169-ee10d348-d8df-413b-9051-7bff0d3c4de8.png">

default protein:
<img width="549" alt="image" src="https://user-images.githubusercontent.com/92519311/182986239-6ac68f0e-4d39-4b2c-be26-f6dad0c5a4c3.png">


Both worked. Thx for your help!
