### ISSUE TITLE
--trace_model performance

### ISSUE THREAD

**Issue by mrhoag5** [aqlaboratory/openfold#191]
Hi, I have tested using the --trace_model mode on a small batch of sequences of the same length; I get an 80s tracing time followed by 20s inference for each sequence. If I just fold them without --trace_model it takes 18-19s for inference of each. Am I doing something wrong? There doesn't seem to be much documentation about this feature.

**Comment by gahdritz** [comment]
This feature is under active development and will be improving soon, but you should still see a speedup using the current version. Which version of torch are you using? To get the most out of tracing it's important that you use torch >= 1.12.0.

**Comment by mrhoag5** [comment]
Thanks, I'm using 1.12.0+cu116.

**Comment by gahdritz** [comment]
What kind of GPU?

**Comment by mrhoag5** [comment]
I'm using an RTX 3060. I just placed the separate fasta files in the input directory and ran run_pretrained_openfold.py on that directory with --trace_model enabled. Is there anything else I need to do? I also had --use_precomputed_alignments enabled, btw. Thanks for the help.

**Comment by gahdritz** [comment]
Sit tight until I upload the new version of tracing (should be fairly soon).

**Comment by mrhoag5** [comment]
Sure thing, thanks!

**Comment by songkevinc** [comment]
Hi @gahdritz just curious, any updates on this? Is the `trace_model` usable now?

**Comment by gahdritz** [comment]
Whoops forgot to close this. It should work fine now, especially for shorter proteins (< 1000 residues).
