### ISSUE TITLE
Dataset Size Info

### ISSUE THREAD

**Issue by merdivane** [aqlaboratory/openfold#193]
Hi, could you please provide the sizes of the datasets especially for pdb_mmcif(how many files will there be in total) in order to check if downloads are completed correctly?

**Comment by gahdritz** [comment]
Check out the RODA documentation here: https://docs.google.com/document/d/1R90-VJSLQEbot7tgXF3zb068Y1ZJAmsckQ_t2sJTv2c/edit

**Comment by merdivane** [comment]
I was asking about the dataset size for files in download_data.sh especially after running the script below:

"Downloading PDB mmCIF files..."
bash "${SCRIPT_DIR}/download_pdb_mmcif.sh" "${DOWNLOAD_DIR}"

How many files I should except?

**Comment by gahdritz** [comment]
The sizes are all in the documentation: about 132k PDB mmCIF files and 270k distillation MSAs.
