### ISSUE TITLE
Data_transforms.py bug

### ISSUE THREAD

**Issue by lupoglaz** [aqlaboratory/openfold#20]
Line:
https://github.com/aqlaboratory/openfold/blob/03bb003a9d61ed0a0db66bb996f46b1754d7d821/openfold/data/data_transforms.py#L1139

should not exist. Otherwise most of the features are empty, when there are no templates.
See corresponding line in the original AF2:

https://github.com/lupoglaz/alphafold/blob/2d53ad87efedcbbda8e67ab3be96af769dbeae7d/alphafold/model/tf/data_transforms.py#L524

**Comment by gahdritz** [comment]
I'm not sure I follow---that variable is only used to crop template features. When there are no templates, it crops only the nonexistent templates to 0.

**Comment by lupoglaz** [comment]
Yes, sorry. It was a bug in my code, yours is perfectly fine.
