### ISSUE TITLE
IndexError when running long_sequence_inference

### ISSUE THREAD

**Issue by brianloyal** [aqlaboratory/openfold#209]
Hey team, I've started experimenting with the long_sequence_inference configuration and am getting an error. This one was for 6XOS (1014 aa), though I'm seeing the same thing for other large proteins as well:

1661791268948,INFO:/opt/openfold/run_pretrained_openfold.py:Loaded   OpenFold parameters at /database/openfold_params/finetuning_ptm_2.pt...
--
1661791268948,INFO:/opt/openfold/run_pretrained_openfold.py:Using   precomputed alignments for 6XOS_1 at /tmp/openfold/msas/...
1661791305211,INFO:/opt/openfold/run_pretrained_openfold.py:Running   inference for 6XOS_1...
1661791306172,Traceback (most recent call   last):
1661791306172,"  File   ""/opt/openfold/run_pretrained_openfold.py"", line 610,   in <module>"
1661791306172,    main(args)
1661791306172,"  File   ""/opt/openfold/run_pretrained_openfold.py"", line 434,   in main"
1661791306172,"    out = run_model(model,   processed_feature_dict, tag, args)"
1661791306172,"  File   ""/opt/openfold/run_pretrained_openfold.py"", line 111,   in run_model"
1661791306172,    out = model(batch)
1661791306172,"  File   ""/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py"",   line 1130, in _call_impl"
1661791306172,"    return forward_call(*input,   **kwargs)"
1661791306172,"  File   ""/opt/openfold/openfold/model/model.py"", line 515, in   forward"
1661791306172,    _recycle=(num_iters > 1)
1661791306172,"  File   ""/opt/openfold/openfold/model/model.py"", line 319, in   iteration"
1661791306172,"    inplace_safe=inplace_safe,"
1661791306172,"  File   ""/opt/openfold/openfold/model/model.py"", line 118, in   embed_templates"
1661791306172,"    batch, z, pair_mask, templ_dim,   inplace_safe=inplace_safe,"
1661791306172,"  File   ""/opt/openfold/openfold/model/template.py"", line 472,   in embed_templates_offload"
1661791306172,"      _mask_trans=model.config._mask_trans,"
1661791306172,"  File   ""/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py"",   line 1130, in _call_impl"
1661791306172,"    return forward_call(*input,   **kwargs)"
1661791306172,"  File   ""/opt/openfold/openfold/model/template.py"", line 373,   in forward"
1661791306172,    expand_idx[-3] = t.shape[-4]
1661791306172,IndexError: tuple index out   of range

This is on an AWS G5.xlarge instance (4 vCPU, 16 GiB Memory, 24 GiB GPU Memory) running the main branch OF code from today.

**Comment by gahdritz** [comment]
Fixed in 12caaa8.
