### ISSUE TITLE
ddp error

### ISSUE THREAD

**Issue by liuxm117** [aqlaboratory/openfold#21]
when i use strategy='ddp', train_openfold.py error, follows:

RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 4983 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

**Comment by gahdritz** [comment]
Are you running the model with DeepSpeed?

**Comment by liuxm117** [comment]
yes , with deepspeed ,the model can run. if don't use activation checkpointing ,does ddp ok?

**Comment by gahdritz** [comment]
Yes, if you don't use activation checkpointing, native DDP would work. However, I'm not aware of a graphics card with enough memory to run the full model at the scale of AlphaFold 2 without it.
