### ISSUE TITLE
A question about a confusing scaling operation in masked_msa_loss function

### ISSUE THREAD

**Issue by SYW23** [aqlaboratory/openfold#218]
Hi

I notice that there is a scaling operation in this function:
https://github.com/aqlaboratory/openfold/blob/7384e2d6a763c52580bea07eb8b16f11c02e8322/openfold/utils/loss.py#L1493

I'm not sure what is the use of the var _scale_. It seems that it is unnecessary to multiple it to _denom_ by which _loss_ is divided and then multiple it back to _loss_ afterward?

**Comment by gahdritz** [comment]
This is a trick to stabilize FP16 training.
