### ISSUE TITLE
Invalid Command: tar2exprofiledb

### ISSUE THREAD

**Issue by yuzhiguo07** [aqlaboratory/openfold#22]
in openfold/scripts/prep_mmseqs_dbs.sh
I guess it should be `mmseqs tsv2exprofiledb` not `mmseqs tar2exprofiledb`

Also a bug at line 26: `tar --extract --verbose --file="${DOWNLOAD_DIR}/${f}" \`
I think it should be `tar --extract --verbose --file="${f}" \`

**Comment by gahdritz** [comment]
Right on both counts. Fixed in 78e7996.
