### ISSUE TITLE
bug: wrong transition updates?

### ISSUE THREAD

**Issue by lihuiknight** [aqlaboratory/openfold#220]
The function `__mul__` in Rigid conducts a composition of transformation.  The new_trans is updated by `new_trans = self._trans * right[..., None]`. it seems a bug. According to the equation in page.4 from af2 appendix, it could be `new_trans = self._trans + self._trans * right[..., None]`.

**Comment by gahdritz** [comment]
`__mul__` is not the composition of transformations. It is the pointwise multiplication of a transformation by a tensor, and is used for e.g. masking. The function you're looking for is `compose`.
