### ISSUE TITLE
Acquiring MSAs

### ISSUE THREAD

**Issue by cutecows** [aqlaboratory/openfold#25]
Thanks so much for an excellent repo!

I'm trying to weigh all of the options for acquiring MSAs in order to train the model. I could either 1) use trrosetta's MSAs, 2) Use Protein Net's MSAs, or 3) Make MSAs myself using MMSeqs2. Do you potentially know how these options compare and how long 3) would take?

Thanks!

**Comment by gahdritz** [comment]
Like you said, 1) and 2) would be much faster, and would probably suffice for the vast majority of use cases. The time 3) takes depends entirely on the number of CPUs you have, but it'll be a substantial time investment for almost anyone.

**Comment by cutecows** [comment]
Thanks so much!

**Comment by alquraishi** [comment]
Should add that we will be making the full MSAs (#3) publicly available as well.
