### ISSUE TITLE
Why is `use_memory_efficient_kernel` always set to `False`

### ISSUE THREAD

**Issue by RuiWang1998** [aqlaboratory/openfold#261]
Hi all,

Thanks for this great implementation. I was wondering why `use_memory_efficient_kernel` is now always False even in the row-attention modules.

Thanks in advance!

Best

**Comment by gahdritz** [comment]
In most cases, you're better off using `use_lma`. The kernel is most useful during training (because of its in-place backward implementation), where it is enabled by default for the MSARowAttention module in the ExtraMSAStack.
