### ISSUE TITLE
do we have small or middle size dataset to train openfold? 

### ISSUE THREAD

**Issue by chrjxj** [aqlaboratory/openfold#267]
hi experts,  just wonder whether we have small or middle size folding dataset to train with Openfold? I don't have to train a best model end to end.

**Comment by gahdritz** [comment]
The RODA directory is structured so you can download arbitrary subsets of the data there. I recommend sampling ~10,000 proteins from the pdb/ directory and using that as a starting point. As we show in the OpenFold paper, this will get you a model that does about as well on CAMEO proteins as the model trained on all PDB chains (and after just a few iterations, too).

**Comment by chrjxj** [comment]
thank you. very helpful
