### ISSUE TITLE
Purpose of rc.MAP_HHBLITS_AATYPE_TO_OUR_AATYPE

### ISSUE THREAD

**Issue by cutecows** [aqlaboratory/openfold#27]
Hi,

Thanks for a great repo!

I'm confused why the template's amino acids and the msa's amino acids are modified again using rc.MAP_HHBLITS_AATYPE_TO_OUR_AATYPE. 

It seems like we read the amino acids from the pdb structure and convert them to ids using HHBLITS_AA_TO_ID. I'm wondering why we need to modify them again?

**Comment by gahdritz** [comment]
It converts aatype IDs using the HHblits convention to DeepMind's own encoding, which sorts the aatypes alphabetically. It's necessary for reformatting the output of some of the alignment tools.
