### ISSUE TITLE
trained parameters

### ISSUE THREAD

**Issue by rohanvarm** [aqlaboratory/openfold#28]
Hi, will you be releasing the parameters on a non-academic license as well ? Or do we have to train it from scratch?

**Comment by alquraishi** [comment]
Parameters will be released under a permissive license for commercial and non-commercial use.

**Comment by rohanvarm** [comment]
Hi, was just wondering what timeline we should expect the parameters to be released?

**Comment by gahdritz** [comment]
Training is currently ongoing. We haven't set a release date yet, but it should be fairly soon.
