### ISSUE TITLE
CASP 15 results

### ISSUE THREAD

**Issue by empyriumz** [aqlaboratory/openfold#294]
Hi there,

I recently stumbled upon the [CASP 15 results](https://predictioncenter.org/casp15/zscores_final.cgi) and noticed that OpenFold ranked 49 out of 132 teams, while ColabFold ranked 24. I am curious to know if there are any specific reasons why OpenFold performed relatively worse than ColabFold. Do you think it is possible that OpenFold has some bugs at the time of competition that may have affected its performance?

Thank you!

**Comment by gahdritz** [comment]
We participated in CASP while OpenFold was still being trained. After the competition, we recomputed structures for all CASP targets (with none of the manual interventions we performed during the competition). Results for OpenFold (model 1) and AlphaFold (model 1) are plotted below:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/26167235/226080527-33d0993e-64ba-4622-add3-f27dbe10b647.png">

**Comment by yamule** [comment]
I think one of the reasons of the difference is that ColabFold used AlphaFold-Multimer while OpenFold used AlphaFold2 with the gap trick  for multimer (and its subunit) prediction.

https://predictioncenter.org/casp15/doc/CASP15_Abstracts.pdf

**Comment by jozhang97** [comment]
@gahdritz Thanks for the great opensource work. I would like to reproduce this graph, could you point me to where I can access this data?

I found some at https://predictioncenter.org/download_area/CASP15/targets/ but there are only 45 targets, not 90.
I see 91 targets fitting the "All Groups" filter here https://predictioncenter.org/casp15/targetlist.cgi but not all of them have pdb codes so its not clear how to set up the dataset.
