### ISSUE TITLE
OOM in validation

### ISSUE THREAD

**Issue by lhatsk** [aqlaboratory/openfold#30]
I get CUDA OOM error when I add my validation set, which I can predict just fine with run_pretrained_openfold.py

Are you limiting your validation set to a certain size? I assume the problem is because of the additional features necessary to compute the loss.

I had to do some changes to make validation work:
val needs to be changed to eval in data_modules, e.g.:
https://github.com/aqlaboratory/openfold/blob/main/openfold/data/data_modules.py#L153 

The third argument "unclamped" no longer exists:
https://github.com/aqlaboratory/openfold/blob/main/openfold/data/data_modules.py#L188

Switch validation also to _output_raw=True

**Comment by gahdritz** [comment]
Bugs fixed in 2abd8c1.

DeepMind limited proteins in its evaluation set to 700 residues. If you're still experiencing memory issues on that setting, I suggest adding chunking in the eval config. There's no evidence that DeepMind did that, but there isn't any evidence that they didn't, either.
