### ISSUE TITLE
Validation set used in the OpenFold paper

### ISSUE THREAD

**Issue by meneshail** [aqlaboratory/openfold#322]
Hi,
Thanks for the great work!
A validation set from CAMEO is used throughout the OpenFold paper. I wonder if there is any way to access this validation set (PDB and MSA). Indeed there is a script in this repo that could download the latest CAMEO data, but accessing the very same validation set used in the paper could allow direct and fair comparison to those insightful experiment results, and is very useful in many cases.
Thanks in advance :)

**Comment by gahdritz** [comment]
The script allows you to specify a date range, and the dates for our val set are provided in the OpenFold preprint (Oct 16 2021 - Jan 16 2022).
