### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by sr5434** [aqlaboratory/openfold#326]
What system requirements are needed to train OpenFold? Also, can those requirements be included in the README?

**Comment by gahdritz** [comment]
We trained the public OpenFold parameters on 44 A100s (see full details in the OpenFold preprint). The requirements will vary depending on the use case---if you're not interested in the final finetuning stage of training, for example, you can get away with GPUs with much less memory.

**Comment by sr5434** [comment]
Thanks
