### ISSUE TITLE
No module named 'scripts.utils'

### ISSUE THREAD

**Issue by evancollins1** [aqlaboratory/openfold#329]
I am trying to install `openfold` on Python 3.9.7.

When I run...

`pip install --user openfold`

I get the following error: `No module named 'scripts.utils'`. 

This same error also appears if I use the conda environment approach as suggested in the readme.

How can I resolve this? Thanks.

ERROR: Command errored out with exit status 1:
     command: /home/software/anaconda3/2021.11/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5qnaip8s/openfold_6f7323166ef045288e1d740d281e0b8b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5qnaip8s/openfold_6f7323166ef045288e1d740d281e0b8b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2ur97sqp
         cwd: /tmp/pip-install-5qnaip8s/openfold_6f7323166ef045288e1d740d281e0b8b/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5qnaip8s/openfold_6f7323166ef045288e1d740d281e0b8b/setup.py", line 21, in <module>
        from scripts.utils import get_nvidia_cc
    ModuleNotFoundError: No module named 'scripts.utils'

**Comment by gahdritz** [comment]
Could you share the exact commands you ran for the conda approach?

**Comment by naafey-aamer** [comment]
hello @evancollins1 
 how did you work around this? Facing the same error on Ubuntu
