### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.utils'

### ISSUE THREAD

**Issue by TobiasPol** [aqlaboratory/openfold#341]
I was trying to install openfold with `pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'` and getting the following errror:

```
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_t/p573f1js2w5dx_xvd_h112h40000gn/T/pip-install-642l7elx/openfold_c56845d2684b4f048f7707a25b36ac5a/setup.py", line 21, in <module>
          from scripts.utils import get_nvidia_cc
      ModuleNotFoundError: No module named 'scripts.utils'
```

I tried to install the missing package, but it did not fix the problem.

This problem occurred while trying to install esmfold ([Link to repository](https://github.com/facebookresearch/esm)).

**Comment by sabadaftari** [comment]
I have the same issue, checked the cuda version for Pytorch as they suggested on the esm GitHub but everything is installed on my machine.

**Comment by hzk597955516** [comment]
you need to add a "__init__.py" in the scripts folder.  :-)
