### ISSUE TITLE
how to extract the embeddings for each Protein Sequence

### ISSUE THREAD

**Issue by alip67** [aqlaboratory/openfold#35]
First of all, great work!

As you know for each protein Sequence Evolutionary Scale Modeling(ESM) generates an embedding in the size of #aminoacids*1280, I was wondering if we could get such information from openfold as well. do you think is this possible to extract such an embedding from the inner layers of openfold?
 could you give some guide on how to extract such information from openfold?

Thanks!

**Comment by gahdritz** [comment]
I'm not familiar with this 1280-element embedding. Could you elaborate? Are you talking about what DeepMind calls the "single" embedding?

**Comment by alip67** [comment]
> I'm not familiar with this 1280-element embedding. Could you elaborate? Are you talking about what DeepMind calls the "single" embedding?

Thanks for your quick response. I'm talking about the Evolutionary Scale Modeling(ESM) from FACEBOOK. for each protein sequence they output just one single embedding that represents the whole protein sequence in tabular form #aminoacids*1280. this embedding has information about the protein sequence and I want to extract this from the inner layers of Openfold.  I'm looking for sth like this embedding in the Openfold. could you give me the details about this single embedding from DeepMind? maybe this is the one that I'm looking for.

**Comment by gahdritz** [comment]
It's one of the outputs of the model (I think it's called "single" in the output dictionary), and is derived from the first row of the MSA embedding that comes out of the evoformer. It has shape [N, 384].

**Comment by gahdritz** [comment]
Whoops---didn't mean to close.

**Comment by alip67** [comment]
> 

could you elaborate on the "different points in the model". also I have this question, if I just run the code from the Colab version that you provide, is this information available in the zip file that it generates?

**Comment by gahdritz** [comment]
No, it's not in the output zip by default. You'll have to slightly modify the Colab to extract more stuff from the output dictionary.

As for "different points in the model:" you asked about viewing the single embedding in the "inner layers" of OpenFold. I assumed that meant you want to observe how the single embedding evolves over time. One way to do that would be to inspect its value after each recycling iteration.

**Comment by alip67** [comment]
> No, it's not in the output zip by default. You'll have to slightly modify the Colab to extract more stuff from the output dictionary.
> 
> As for "different points in the model:" you asked about viewing the single embedding in the "inner layers" of OpenFold. I assumed that meant you want to observe how the single embedding evolves over time. One way to do that would be to inspect its value after each recycling iteration.

Thanks for the explanation. could you please also give me some instructions on how to extract these single embeddings from the Colab version or even from the original code that I could follow?

That would be a great help and I really appreciate it.

**Comment by gahdritz** [comment]
The model outputs a dictionary. In the colab, only the structure and plddt scores are currently retrieved from it. Getting the single embedding is as simple as retrieving "single" from the dictionary.
