### ISSUE TITLE
weights for single sequence mode?

### ISSUE THREAD

**Issue by emzodls** [aqlaboratory/openfold#368]
Hi, I'm trying to run openfold in single sequence mode (using ESM1b embeddings). I'm following the instructions on the main page but I don't seem to have the parameters file referenced "seq_model_esm1b_ptm.pt." I tried using "finetuning_no_tmpl_ptm_1.pt" but I got a missing keys errors (trying without the config_preset "seq_model_esm1b_ptm" and with the --use_single_seq_mode flag instead also resulted in missing keys errors though a different set of keys). 

What is the correct way to run openfold in single sequence mode currently, and are there any other parameter files I need to download for this?

**Comment by jnwei** [comment]
Hi, thank you for your interest. The parameter files are now available as of #373 .
