### ISSUE TITLE
Bug in OpenFoldMultimerDataset.deterministic_train_filter

### ISSUE THREAD

**Issue by Zoesgithub** [aqlaboratory/openfold#369]
The description in the manuscript of multimer is 
"We filter out proteins during training if: 
•The input mmCIF has resolution greater than 9Å. 
•Any single amino acid accounts for more than 80% of the complex sequences.
•The example comes from the distillation set and has less than 200 residues."  

But the code is 
' 

    @staticmethod
    def deterministic_train_filter(
        cache_entry: Any,
        is_distillation: bool,
        max_resolution: float = 9.,
        max_single_aa_prop: float = 0.8,
        minimum_number_of_residues: int = 200,
        *args, **kwargs
    ) -> bool:
        """
        Implement multimer training filtering criteria described in
        https://www.biorxiv.org/content/10.1101/2021.10.04.463034v2.full.pdf Supplementary section 7.1
        """
        resolution = cache_entry.get("resolution", None)
        seqs = cache_entry["seqs"]

        return all([resolution_filter(resolution=resolution,
                                      max_resolution=max_resolution),
                    all_seq_len_filter(seqs=seqs,
                                       minimum_number_of_residues=minimum_number_of_residues),
                    (is_distillation and aa_count_filter(seqs=seqs,
                                                         max_single_aa_prop=max_single_aa_prop))])

'
I think it should be

    @staticmethod
    def deterministic_train_filter(
        cache_entry: Any,
        is_distillation: bool,
        max_resolution: float = 9.,
        max_single_aa_prop: float = 0.8,
        minimum_number_of_residues: int = 200,
        *args, **kwargs
    ) -> bool:
        """
        Implement multimer training filtering criteria described in
        https://www.biorxiv.org/content/10.1101/2021.10.04.463034v2.full.pdf Supplementary section 7.1
        """
        resolution = cache_entry.get("resolution", None)
        seqs = cache_entry["seqs"]

        return all([resolution_filter(resolution=resolution,
                                      max_resolution=max_resolution),
                    aa_count_filter(seqs=seqs,
                                                         max_single_aa_prop=max_single_aa_prop),
                    (not is_distillation or all_seq_len_filter(seqs=seqs,
                                       minimum_number_of_residues=minimum_number_of_residues))])

**Comment by dingquanyu** [comment]
Hi,

Thanks a lot for your suggestion. I'm really sorry that these filtering criteria were not put in the correct way. #370 should fix this.

Yours,
Dingquan Yu

**Comment by christinaflo** [comment]
Yes I agree with the above. Although "The example comes from the distillation set and has less than 200 residues" sounded like (is_distillation and all_seq_len_filter(seqs=seqs, minimum_number_of_residues=minimum_number_of_residues) to me. Also since the distillation dataset uses this OpenFoldMultimerDataset object, it would just filter out all the samples for this dataset.

**Comment by christinaflo** [comment]
Oh wait no you're totally right, forgot the filter returns true for including not excluding samples. Pushed a fix in the latest commit, cdeb8d1.
