### ISSUE TITLE
Multimer

### ISSUE THREAD

**Issue by ozsolomon** [aqlaboratory/openfold#37]
Hi,
Thanks for this great work.
Just wondering, is there a way to do complex (multimer) prediction as in alphafold multimer ?

Thanks
Oz

**Comment by gahdritz** [comment]
OpenFold implements AlphaFold v2.0.1, so the release right before AlphaFold-Multimer was announced. However, we're currently working on much more memory-efficient versions of AlphaFold modules, which will make inference on much, much longer sequences possible.

**Comment by ozsolomon** [comment]
Thanks.
Keep with the good work 👍 
I'll pay attention to the next updates.
