### ISSUE TITLE
Is the result "deterministic" when learning for specific dataset and seed?

### ISSUE THREAD

**Issue by vetmax7** [aqlaboratory/openfold#388]
Hello!

I train a model on a small dataset. And I noticed that when I restart the model training process, I get the same loss values for the same parameters and data. But shouldn't it change at least somehow depending on random values during the learning process?

What I mean is that usually when doing computer simulations it's common to do a few runs and then estimate the averages. But here it turns out that the result is the same every time, like it shows below.

Or is it necessary to change the random seed for different runs? Is it possible to compare and average the data later for such cases?

0.0 90.6
1.0 60.1
2.0 58.3
3.0 60.0
4.0 57.4
5.0 133.0
6.0 76.1
7.0 68.3
8.0 61.0
9.0 56.9
10.0 54.8

`python train_openfold.py /pdb_mmcif/mmcif_files/  /alignments/   /pdb_mmcif/mmcif_files/  /output_dir/     "2023-09-01"     --template_release_dates_cache_path  mmcif_cache.json     --precision 32     --gpus 1 --replace_sampler_ddp=True     --seed 4242022 --checkpoint_every_epoch     --train_chain_data_cache_path  chain_data_cache.json     --obsolete_pdbs_file_path obsolete.dat    --log_performance=True `

**Comment by christinaflo** [comment]
Yes it is necessary to change the random seed for different runs. It is expected behavior that you will get the same loss values if you use the same seed value (for reproducibility).
