### ISSUE TITLE
Prediction Reproducibility

### ISSUE THREAD

**Issue by brucejwittmann** [aqlaboratory/openfold#390]
Hi,

Is there a way to enforce deterministic predictions? I have found that the below command will produce slightly different unrelaxed structures even when passing in the same inputs. This is being run inside of a Docker container extended from the Dockerfile provided on the repository.

`
python3 /opt/openfold/run_pretrained_openfold.py <fasta_folder> <mmcif_dir> --use_precomputed_alignments <alignment_dir> --output_dir <outdir> --model_device cuda:<#> --openfold_checkpoint_path <openfold_params> --config_preset model_1_ptm --skip_relaxation --data_random_seed 2
`

I looked in the code and it appears that both the torch and numpy random seeds should be set if `--data_random_seed` is provided. Is there another source of randomness that is not being handled (e.g., hashing)?

**Comment by christinaflo** [comment]
Yes the --data_random_seed option should remove the randomness. Which commit are you using? If it's the latest, could you try running it twice after commenting out the following in run_pretrained_openfold.py: 

`if(
    torch_major_version > 1 or
    (torch_major_version == 1 and torch_minor_version >= 12)
):
    # Gives a large speedup on Ampere-class GPUs
    torch.set_float32_matmul_precision("high")`

Depending on how different the structures are, it's possible this is due to rounding errors.

**Comment by brucejwittmann** [comment]
I've looked into the code more and it seems that this issue is from my misunderstanding of when the seed is set. I assumed that the seed would be set before each prediction when using `--data_random_seed`, but it seems that it is set at the beginning of the run. The duplicates that I was evaluating were run in batched mode where all predictions were made in the same call to `run_pretrained_openfold.py`, so we shouldn't expect them to be the same. Thank you for your help!
