### ISSUE TITLE
Checkpointing Issue

### ISSUE THREAD

**Issue by cutecows** [aqlaboratory/openfold#40]
Thanks for such a great repo! I get the following issue when running the model (but only when I use GPUs). I'm using torch checkpointing, not deepspeed. I saw an issue similar to this, but it seemed to be deepspeed-specific so I thought I'd repost.

RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 2000 with name module.model.evoformer.blocks.19.pair_transition.linear_2.bias [For reference I have 20 blocks ] has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.

**Comment by gahdritz** [comment]
If you're going to be training on more than one GPU, we recommend DeepSpeed, partly for this reason. The native PyTorch DDP implementation doesn't interact very well with activation checkpointing (if you're curious, look up the "find_unused_parameters" option). Basically you have to choose between having activation checkpoints and using every single parameter in the model for every forward pass, which isn't ideal. DeepSpeed doesn't have such requirements. If you really want to avoid DeepSpeed (which also has memory/runtime advantages over the native stuff), change `strategy = "ddp"` to `strategy = DDPPlugin(find_unused_parameters=False)` in `train_openfold.py`.
