### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by liuxm117** [aqlaboratory/openfold#41]
when i use script_preset_(model_module), code error, 
RuntimeError:
'Tensor' object has no attribute or method 'new_ones'.:
  File "openfold/openfold/model/msa.py", line 118
        if mask is None:
            # [*, N_seq, N_res]
            mask = m.new_ones(
                   ~~~~~~~~~~ <--- HERE
                m.shape[:-3] + (n_seq, n_res),
            )

**Comment by gahdritz** [comment]
This one I'm unable to reproduce. What version of torch are you running?

**Comment by liuxm117** [comment]
torch 1.9.0
python train_openfold.py ../database/pdb_mmcif/mmcif_files ../openfold/alignment_dir ../database/pdb_mmcif/mmcif_files ./output_dir 2021-10-10 --template_release_dates_cache_path ../openfold/mmcif_cache.json --precision 16 --gpus 1 --seed 42 --log_every_n_steps=5 --max_epochs=20

**Comment by gahdritz** [comment]
Try torch 1.10
