### ISSUE TITLE
"Module 'Attention' has no attribute 'linear_g' : "

### ISSUE THREAD

**Issue by ozsolomon** [aqlaboratory/openfold#42]
Hi,
When I'm trying to train the model and running this command :

python /data/openfold/train_openfold.py /home/ubuntu/train_mmcif_Dec29_2021/ //home/ubuntu/ProteinNet_parsed/ProteinNet_MSA/ /data/af_databases/pdb_mmcif/mmcif_files/ /home/ubuntu/OF_train_from_ProteinNet_try1_Dec29_20210/ 2021-10-10 --template_release_dates_cache_path /data/af_databases/pdb_mmcif/mmcif_cache.json --precision 16 --replace_sampler_ddp=True --deepspeed_config_path /data/deepspeed_config.json --resume_from_ckpt ckpt_dir/ --gpus 1 --precision 16 --seed 44

I get this error -

"Module 'Attention' has no attribute 'linear_g' : "

I'm running it from the conda env (openfold_venv)

Thanks
Oz

**Comment by lhatsk** [comment]
https://github.com/aqlaboratory/openfold/blob/96709588dd6759a02a2eca8b67a278bd3219a3f9/openfold/model/primitives.py#L221

This is not working for some reason. If you change it to the previous version (is not None) it works.

**Comment by gahdritz** [comment]
Fixed in b47138d. I had forgotten why the if statement was written the way it was and made it more idiomatic, breaking TorchScript for this module.
