### ISSUE TITLE
Is the pdb_mmcif.zip from OpenProteinSet on AWS suitable for RODA training data?

### ISSUE THREAD

**Issue by zouzh14** [aqlaboratory/openfold#424]
Dear OpenFold community,

Thanks for you great contribution and the generous sharing of the OpenProteinSet dataset. And I try to use the RODA MSAs to train a model only with data from PDB. And here I noticed you store a pdb_mmcif.zip file on AWS. It is compatible with your RODA MSAs? For you mentioned OpenFold data needs different cifs with AlphaFold, and I want to make sure it's OK.

If the zip file contains the proper structures, do they share the same sequence as the current published cif from RCSB PDB website? Because when I use openfold/scripts/data_dir_to_fasta.py to collect sequences for clustering, there is some bugs and I need to find some alternative sequences for the chains. For instance,

`
python openfold/scripts/data_dir_to_fasta.py  openfold_data/OpenProteinSet/mmcif_files/  openfold_data/OpenProteinSet/seq_cluster/

WARNING:root:Failed to parse 3f2x.cif...
WARNING:root:Failed to parse 3d0u.cif...
WARNING:root:Failed to parse 4hqh.cif...
`

Wishes.

**Comment by ljarosch** [comment]
Hi @zouzh14 , I see you marked this as closed but for anyone else landing on this in the future, the pdb_mmcif.zip does in fact contain all of the structure files corresponding to the RODA MSAs. This is an older snapshot of the PDB, so while the sequences should be compatible with the stored MSAs, newer versions of those structures in the PDB may have slightly altered sequences if they got updated by the authors in the meantime.

Regarding parsing issues, the examples you shared are nucleic acid structures which OpenFold does not support, so the parser ignoring them is nothing to worry about.

Let us know if you encounter any other issues
