### ISSUE TITLE
Docker build broken

### ISSUE THREAD

**Issue by vaclavhanzl** [aqlaboratory/openfold#434]
The docker build used for PR tests is likely broken. See [this docker build](https://github.com/aqlaboratory/openfold/actions/runs/8861858125) which failed when testing a tiny unrelated change in the Colab notebook. I bet the current `main` would not build either.

**Comment by vaclavhanzl** [comment]
Looks like the flash-attention cannot be built in the ancient environment of `main` anymore. I tried:
- local build of the environment - fails the same way as the docker build
- local build of the environment in the `pl_upgrades` branch - works OK
- local build of the environment with flash-attention commit changed from `5b838a8` to `9a11f44` (their current `main`) - fails the same way as the docker build

Maybe it's time to seriously consider the merge of `pl_upgrades` (which may be painful as `main` diverged quite far)?

The idea of fixed versions is nice but only gets us so far - we are always struggling in Colab which is like building on a moving sand and docker build is not building on a rock frozen base either.

**Comment by vaclavhanzl** [comment]
Fixed by #437. Thank you @jnwei.
This can be closed I think.

**Comment by jnwei** [comment]
Great, thanks for reporting the issue @vaclavhanzl , glad the fix takes care of it.

We are still aiming to upgrade to pytorch2 and merge in the changes from pl_upgrades, but we ran into some technical issues. I will share more on this later in the week.

**Comment by vaclavhanzl** [comment]
Thanks @jnwei !
