### ISSUE TITLE
ModuleNotFoundError: No module named 'attn_core_inplace_cuda'

### ISSUE THREAD

**Issue by pikruse** [aqlaboratory/openfold#445]
I am using openfold as a dependency for another package. Whenever the dependency calls `openfold/openfold/utils/kernel/attention_core.py`, I get this error:

`ModuleNotFoundError: No module named 'attn_core_inplace_cuda'`

I've tried looking elsewhere, but I can't find any documentation for this module.

Steps to recreate:
1. clone the `openfold` repo
2. create `openfold_env` as per the openfold installation instructions
3. run the `openfold/utils/kernel/attention_core.py` with python, e.g. `python3 openfold/utils/kernel/attention_core.py`

I am working on a computing cluster with CUDA version 12.2.

**Comment by sachinkadyan7** [comment]
Hey @pikruse ,

As @dingquanyu mentioned the attention kernel issue should be solved once you get OpenFold built and installed using `python setup.py install`. I am closing this for now but feel free to reopen if you face any further issues.
