### ISSUE TITLE
Questions about the meaning of folder naming conventions in OpenProteinSet

### ISSUE THREAD

**Issue by lonelycrab888** [aqlaboratory/openfold#449]
![image](https://github.com/aqlaboratory/openfold/assets/115449596/99b10ca8-f1af-4e93-99e3-3257a1897601)
May I know what the difference is between these two folders——alignment_db and pdb?

**Comment by ljarosch** [comment]
Hi @lonelycrab888, sorry for the late reply. The `alignment_db/` directory represents a different format for storing the alignments in the `pdb/` directory which can be faster for I/O-bottlenecked systems. You can find more information about this [in the docs](https://openfold.readthedocs.io/en/latest/OpenFold_Training_Setup.html#creating-alignment-dbs-optional)
