### ISSUE TITLE
The parameter mmcif_dir in precompute_alignments.py

### ISSUE THREAD

**Issue by XXXXXcoder** [aqlaboratory/openfold#45]
I need to precompute protein alignments before training the model, but I didn't find the path mmcif_dir/.

**Comment by gahdritz** [comment]
The downloads include no precomputed alignments---those you'll need to generate yourself. We do provide scripts for downloading the required databases and also a simple script that runs the actual alignment (instructions for which are provided in the README). Let me know if you have any further questions.

**Comment by XXXXXcoder** [comment]
> The downloads currently include no precomputed alignments---those you'll need to generate yourself. We do provide scripts for downloading the required databases and also a simple script that runs the actual alignment (instructions for which are provided in the README). Let me know if you have any further questions.
> 
> (We do plan to release a large dataset of AlphaFold training MSAs soon, however. Stay tuned)

Yeah, I intend to generate alignments by runing "precompute_alignments.py", but I need to input the path "mmcif_dir/" as a parameter in precompute_alignments.py, then I cannot find the path "mmcif_dir", so I don't know which proteins need to be aligned before training the model.
![image](https://user-images.githubusercontent.com/35370756/147800250-6988615d-6b85-41b5-beed-73fdab46b97a.png)

**Comment by gahdritz** [comment]
`input_dir` is just a directory containing target files you want to run the alignments on. It can contain .cif mmCIF files, FASTA files, or ProteinNet .core files. If you want to use the same data as AlphaFold and have downloaded `pdb_mmcif`, then the value of `input_dir` would be `<path_to_dir>/pdb_mmcif/mmcif_files`

**Comment by XXXXXcoder** [comment]
get it! Thanks for your reply.
