### ISSUE TITLE
about self.cached_weights

### ISSUE THREAD

**Issue by wangleshuyang** [aqlaboratory/openfold#46]
Why do I report this error when I specify the validation set during training: AttributeError:'OpenFoldWrapper' object has no attribute'cached_weights'

**Comment by lhatsk** [comment]
Add         self.cached_weights = None to the __init__ method of the OpenFoldWrapper in train_openfold.py

**Comment by gahdritz** [comment]
Added in 30e051c

**Comment by wangleshuyang** [comment]
> 



> Fixed in [30e051c](https://github.com/aqlaboratory/openfold/commit/30e051cf78f27a55de36ad96efad07193db277c2)

Thank you for your help. I also found an error in data_modules.py. Your verification model defines'val' on line 93, but you write mode="eval" in some code, and you use it on lines 156, 476, 498, and 524. 'eval' is in data_modules.py.

**Comment by gahdritz** [comment]
Good catch. Thanks!
