### ISSUE TITLE
Has the self-distillation database with 270,000 structures been provided, and where can I find it? Or do I need to generate it myself?

### ISSUE THREAD

**Issue by muuu23333** [aqlaboratory/openfold#466]

**Comment by ljarosch** [comment]
Hi, this is provided in [OpenProteinSet](https://registry.opendata.aws/openfold/) in the `uniclust30/` directory. Also see the documentation [here](https://docs.google.com/document/d/1R90-VJSLQEbot7tgXF3zb068Y1ZJAmsckQ_t2sJTv2c/edit)
