### ISSUE TITLE
the consuming time for precompute alignments

### ISSUE THREAD

**Issue by XXXXXcoder** [aqlaboratory/openfold#47]
I ran "precompute_alignments.py" to precompute 184,700 protein alignments before training the model because I want to use the same data as AlphaFold, but It took me ~4h to finish only one protein alignment (1yxq), so I want to know my operation is correct or not, besides, is there any precomputed alignments can be download to save my aligned time?

**Comment by gahdritz** [comment]
To compute the full set, you'll need many thousands of CPU cores for several weeks. That dataset is not currently available, but our lab has computed it and will be releasing it relatively soon.
