### ISSUE TITLE
mmseqs tsv2exprofiledb issue with colabfold_envdb_202108

### ISSUE THREAD

**Issue by jacknicoludis** [aqlaboratory/openfold#52]
I was having issues with the prep_mmseqs_db.sh script, so I tried running the steps individually and I'm having an issue with running `mmseqs tsv2exprofiledb` with the `colabfold_envdb_202108` database.

First, I downloaded this databases using the `download_mmseqs_dbs.sh` script and then ran the `tar` command according to the example in `prep_mmseqs_dbs.sh` such that I had a directory with the following files:
```
colabfold_envdb_202108.tsv           
colabfold_envdb_202108_seq.tsv  
colabfold_envdb_202108_aln.tsv 
colabfold_envdb_202108_h.tsv 
uniref30_2103.md5sums
uniref30_2103.tsv
uniref30_2103_h.tsv
uniref30_2103_aln.tsv  
uniref30_2103_seq.tsv
```

I then used `mmseqs tsv2exprofiledb mmseqs_dbs/uniref30_2103 /mmseqs/uniref30_2103_db` which seemed to complete without error (though there is no .idx file, which is supposed to be the output of this command, I believe), generating the following files:
```                
uniref30_2103_db.dbtype    
uniref30_2103_db_seq_tmp
uniref30_2103_db.index     
uniref30_2103_db_seq_tmp.index.0
uniref30_2103_db.sh
uniref30_2103_db_h
uniref30_2103_db.0
uniref30_2103_db.1               
uniref30_2103_db_h.dbtype
uniref30_2103_db_h.index
```         

However, when I tried to do the same with the colabfold_envdb_202108 database, it seemed to start correctly, but then was `killed` after a minute or two. The following files were generated:
```
colabfold_envdb_202108_db.sh   
colabfold_envdb_202108_db_h     
colabfold_envdb_202108_db_h.index.0  
```

I used `nohup` and this is the extent of the output from that command:
```
tsv2exprofiledb /mmseqs_dbs/colabfold_envdb_202108 /mmseqs_dbs/colabfold_envdb_202108_db

MMseqs Version: 4f046dd1979ec87b440656ff13b12e5c525b8374
Verbosity       3

Killed
```

I'm wondering if I'm using an instance with insufficient RAM. Do you have an idea of the amount of RAM needed for the idx files?

**Comment by gahdritz** [comment]
This is a question for the HH-suite GitHub, I'm afraid. I think it might be memory-related, but I'm not sure.

**Comment by jacknicoludis** [comment]
I started an instance with significantly more ram and it seems like it is working, so I will close this - thanks

**Comment by wewewexiao2008** [comment]
Hello, @jacknicoludis  I followed your command `mmseqs tsv2exprofiledb mmseqs_dbs/uniref30_2103 /mmseqs/uniref30_2103_db`, and it's true that there is no .idx file generated, which is supposed to be used by `precompute_alignments_mmseqs.py`. Could you tell me what should be done to generate this one?
