### ISSUE TITLE
Sampling recycling iterations in validation

### ISSUE THREAD

**Issue by lhatsk** [aqlaboratory/openfold#56]
I was a bit surprised that the number of recycling iterations are sampled during validation. This makes different validation epochs less comparable and the progress less smooth. I think eval should mimic predict in this aspect.

    max_iters = self.config.common.max_recycling_iters
    if(stage_cfg.supervised):
        clamp_prob = self.config.supervised.clamp_prob
        keyed_probs.append(
            ("use_clamped_fape", [1 - clamp_prob, clamp_prob])
        )

    if(self.stage == "train" and self.config.supervised.uniform_recycling):
        recycling_probs = [
            1. / (max_iters + 1) for _ in range(max_iters + 1)
        ]
        keyed_probs.append(
            ("no_recycling_iters", recycling_probs)
        )
    else:
        recycling_probs = [
            0. for _ in range(max_iters + 1)
        ]
        recycling_probs[-1] = 1.
        keyed_probs.append(
            ("no_recycling_iters", recycling_probs)
        )

**Comment by gahdritz** [comment]
Could you make a pull request with this change and the progress bar fix?
