### ISSUE TITLE
Clamped fape loss in validation

### ISSUE THREAD

**Issue by lhatsk** [aqlaboratory/openfold#57]
Currently, the fape loss is clamped in 90% of the cases during validation. I'm wondering if this should be made deterministic (always clamp or never clamp) to make validation runs more comparable.

**Comment by lhatsk** [comment]
It's a non-issue if you follow the DeepMind evaluation setup. They are only tracking IDDT-CA.

**Comment by gahdritz** [comment]
Ours should also follow that setup. I'll update it soon.

**Comment by gahdritz** [comment]
This is now fixed.
