### ISSUE TITLE
About multimer

### ISSUE THREAD

**Issue by Ericzhang1** [aqlaboratory/openfold#59]
If any chance, will multimer be updated in the future?

**Comment by gahdritz** [comment]
We don't have plans to implement multimer directly anytime soon. However, we have implemented and will soon (~1 week) be releasing several optimizations that will make possible inference on much longer sequences than the original can handle.

**Comment by alquraishi** [comment]
While not a top priority for us at the moment, once we have a trained version of OpenFold done we will move on to training variants including multimer.

**Comment by moritzschaefer** [comment]
Are there any updates regarding this issue?

**Comment by gahdritz** [comment]
Multimer is fully implemented and will be uploaded this week.

**Comment by RegiusQuant** [comment]
Looking forward to being able to use Openfold-Multimer

**Comment by gahdritz** [comment]
Sorry --- this got held up a little bit. I'll circle back here once it's up.

**Comment by RegiusQuant** [comment]
Is there any updates about multimer now？  (•‿•)

**Comment by gahdritz** [comment]
So sorry for the repeated delays on this; I've had my hands full with CASP stuff recently. I've recently pushed all of the multimer stuff I have to the `multimer` branch. It's not as polished as I'd like it to be, but multimer inference should work now.
