### ISSUE TITLE
About template angle information

### ISSUE THREAD

**Issue by Ericzhang1** [aqlaboratory/openfold#60]
I notice that when computing template information, 'template_angle_embedding' and 'angle' are processed as features. However, I did not see such feature keys in the original af code. How was template angle related information computed?

**Comment by gahdritz** [comment]
See [this block](https://github.com/deepmind/alphafold/blob/1d43aaff941c84dc56311076b58795797e49107b/alphafold/model/modules.py#L1823) from the original. That corresponds to [this part of OpenFold](https://github.com/aqlaboratory/openfold/blob/70d6bda5858e4baded80895c6ed5248de33059ca/openfold/model/model.py#L122)
