### ISSUE TITLE
About ExtraMSA stack 

### ISSUE THREAD

**Issue by Ericzhang1** [aqlaboratory/openfold#64]
The extraMSA stack was giving me out of memory issues even with chunking and checkpointing. I am training with batch 1 on 32gb gpu. However, it seems like people are running with extraMSA with no problem (in other issue post). I was wondering what parameter should I  set for the extraMSA stack? I am guessing the fp16 will consume less memory compare to fp32?

**Comment by gahdritz** [comment]
Yes, the extra MSA stack is extremely memory-intensive. To give you an idea, using the finetuning config, the attention logits in the MSARowAttention module there alone are of shape [1, 5120, 8, 384, 384]. In full precision, that's 24GB for that one tensor alone. The attention module in torch allocates two such tensors, so you'd need 48GB for that layer alone. For that reason, it's highly recommended to train in half precision, like DeepMind did. FP16 training is a little brittle at the moment, but in the next release we'll have vastly improved MSARowAttention memory behavior (already done), efficient attention modules (in progress), and full bfloat16 support on compatible hardware (also done).

**Comment by jonathanking** [comment]
Hi @gahdritz, thanks for the explanation above. It seems like you have provided a great selection of memory efficient configurations. Now that some of the ones you mentioned have been implemented, what settings would you recommend for users constrained by GPU memory, with the goal of replicating the original training/finetuning configurations as much as possible?

**Comment by gahdritz** [comment]
Check out the "long_sequence_inferene" mode. It's exact (not an approximation) and uses much less memory than the stock version.
