### ISSUE TITLE
loss reweighting by sequence length.

### ISSUE THREAD

**Issue by guolinke** [aqlaboratory/openfold#65]
from section 1.9, Suppl. Material
> "To decrease the relative importance of short sequences, we multiply the final loss of each training example by the square root of the number of residues after cropping. This implies equal weighting for all proteins that are longer than the crop size, and a square-root penalty for the shorter ones."
But this seems missing in openfold.

**Comment by gahdritz** [comment]
Good catch---I had missed this. This is indeed missing from OpenFold. I'll add it tomorrow.

**Comment by gahdritz** [comment]
Fixed in 894905b.
