### ISSUE TITLE
About recycling loss

### ISSUE THREAD

**Issue by Ericzhang1** [aqlaboratory/openfold#68]
In the original af paper,  I see that the loss for each recycling iteration is averaged, whereas in openfold, only the loss for last iteration is calculated?

**Comment by gahdritz** [comment]
As far as I know, this is not the case. The first N-1 recycling iterations are run with grad disabled, so it wouldn't make sense to use loss from previous iterations. Are you thinking of the backbone loss, which uses intermediate structures from within the structure module of the final recycling iteration?

**Comment by Ericzhang1** [comment]
So their paper, page 41 in the supplementary, they mention that they use this strategy for recycling. But what u say makes sense.

**Comment by gahdritz** [comment]
I see what you mean. That's just an idealized loss, which they approximate by sampling a random number of recycling iterations. See the followup discussion on page 42.
