### ISSUE TITLE
Multiple Protein Sequences

### ISSUE THREAD

**Issue by alip67** [aqlaboratory/openfold#72]
Hi 

First of all Great work, just a question : 
1- it seems that the Colab version doesn't work because it depends on the requirments.txt file and you just updated this version to work with the environmnet.yml file. I already take care of the Colab so if you want I could push my code to the branch to make it compatible with these new changes. 

2- is this possible to pass multiple protein sequences to the file and get the predictions with a list of sequences?

**Comment by gahdritz** [comment]
The Colab should be fixed now. 

As for 2., the Colab doesn't currently support multiple sequences. The local version does, though.
