### ISSUE TITLE
Bug in affine_utils.py

### ISSUE THREAD

**Issue by wengong-jin** [aqlaboratory/openfold#8]
Hi,

Thanks for the great effort. I was looking at https://github.com/aqlaboratory/openfold/blob/a933bc7479a13e4fcb95f7c7d7ffb9a6b55b0d4f/openfold/utils/affine_utils.py#L282

I wonder this line should be 
```translation = -1 * ca_xyz``` rather than ```translation = -1 * c_xyz```?

**Comment by gahdritz** [comment]
Great catch! You're right. Fixed in d01f47a.
