### ISSUE TITLE
HHbilts error while runing openfold inference

### ISSUE THREAD

**Issue by ozsolomon** [aqlaboratory/openfold#83]
Hi,
Openfold is a great tool and I use it for diff. projects now.
Yesterday while running openfold with AF pre-trained model, I stumbled upon a new error massage that I did not saw in previous runs:

ERROR:root:HHblits failed. HHblits stderr begin:
ERROR:root:- 16:48:14.153 INFO: Searching 65983866 column state sequences.
ERROR:root:- 16:48:15.187 INFO: Searching 15161831 column state sequences.
ERROR:root:- 16:48:15.286 INFO: /home/ubuntu/output_alphafold/monomer/Brazzein_proj/tmp.fasta is in A2M, A3M or FASTA format
ERROR:root:- 16:48:15.287 INFO: Iteration 1
ERROR:root:- 16:48:15.654 INFO: Prefiltering database
ERROR:root:- 16:53:02.200 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 6035472
ERROR:root:- 16:54:29.786 WARNING: Number of hits passing 2nd prefilter (reduced from 343416 to allowed maximum of 100000).
ERROR:root:You can increase the allowed maximum using the -maxfilt <max> option.
ERROR:root:- 16:55:28.667 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 1143029
ERROR:root:- 16:55:54.691 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 188307
ERROR:root:- 16:55:54.691 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 188307
ERROR:root:- 16:55:54.691 INFO: Scoring 188307 HMMs using HMM-HMM Viterbi alignment
ERROR:root:- 16:55:54.820 INFO: Alternative alignment: 0
ERROR:root:- 16:55:57.482 INFO: 2000 alignments done
ERROR:root:- 16:55:59.000 INFO: 4000 alignments done
ERROR:root:- 16:56:02.534 INFO: 6000 alignments done
ERROR:root:- 16:56:05.121 INFO: 8000 alignments done
ERROR:root:- 16:56:07.618 INFO: 10000 alignments done
ERROR:root:- 16:56:10.144 INFO: 12000 alignments done
ERROR:root:- 16:56:12.687 INFO: 14000 alignments done
ERROR:root:- 16:56:15.104 INFO: 16000 alignments done
ERROR:root:- 16:56:17.543 INFO: 18000 alignments done
ERROR:root:- 16:56:19.974 INFO: 20000 alignments done
ERROR:root:- 16:56:22.395 INFO: 22000 alignments done
ERROR:root:- 16:56:24.840 INFO: 24000 alignments done
ERROR:root:- 16:56:27.296 INFO: 26000 alignments done
ERROR:root:- 16:56:29.683 INFO: 28000 alignments done
ERROR:root:- 16:56:32.056 INFO: 30000 alignments done
ERROR:root:- 16:56:34.498 INFO: 32000 alignments done
ERROR:root:- 16:56:37.389 INFO: 34000 alignments done
ERROR:root:- 16:56:39.985 INFO: 36000 alignments done

I am using AWS machine in p3.2xlarge type:
8 cores, 1 gpu, 59G RAM.

From what I saw on AF github, it is related to number of gpus or hhlibs version:
https://github.com/deepmind/alphafold/issues/97

My questions are :
1). Is this is the case also with openfold?
2). How I can change the running  parameters in order to bypass this error with openfold ?
3). Do I need to pay special attention to long proteins (say like > 800aa ) ?

Thanks,
Oz

**Comment by gahdritz** [comment]
Glad to hear you like the tool! Which database is this? My impression is that you might have too little RAM.

**Comment by nsridhar1** [comment]
Indeed a great tool that probably forced AF2 to change their license!

@gahdritz :  How much RAM do you ask for alignments in a production run?
Also, any plans of releasing all hhblits alignments that you used for training the network?

**Comment by ozsolomon** [comment]
Hi,
Thanks you for the replies.
Just to notice that I increased the RAM (and also gpus) by using p3.8xlarge machine and it solved the problem.
Have a nice day,
Oz

**Comment by gahdritz** [comment]
@nsridhar1 I haven't had the opportunity to benchmark this. I'd imagine it depends on sequence length and database size, but I'm not sure. We will be releasing all of the MSAs used to train OpenFold in short order.

**Comment by paulhtyang** [comment]
Hi all,

I am having the same issue but am running on the CPU platform with a stand-alone Linux server (96 cores + 754GB of RAM). I also consider the setting of JAX memory allocation, and below is my command for this Multimer inference purpose. Please share any ideas that can help! Thanks.

------------------------------------------------------------------------------------------------------------------
XLA_PYTHON_CLIENT_ALLOCATOR=platform nohup python3 run_pretrained_openfold.py \
    /bio/projects/protein/openfold/inputs/4M5Y \
    /bio/projects/protein/openfold/data/mmcif_files/ \
    --uniref90_database_path data/uniref90/uniref90.fasta \
    --mgnify_database_path data/mgnify/mgy_clusters_2022_05.fa \
    --pdb_seqres_database_path data/pdb_seqres/pdb_seqres.txt \
    --uniref30_database_path data/uniref30/UniRef30_2021_03 \
    --uniprot_database_path data/uniprot/uniprot.fasta \
    --bfd_database_path data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
    --jackhmmer_binary_path /data/tools/miniforge3/envs/openfold/bin/jackhmmer \
    --hhblits_binary_path /data/tools/miniforge3/envs/openfold/bin/hhblits \
    --hmmsearch_binary_path /data/tools/miniforge3/envs/openfold/bin/hmmsearch \
    --hmmbuild_binary_path /data/tools/miniforge3/envs/openfold/bin/hmmbuild \
    --kalign_binary_path /data/tools/miniforge3/envs/openfold/bin/kalign \
    --config_preset "model_1_multimer_v3" \
    --model_device "cpu" \
    --cpus 64 \
    --long_sequence_inference \
    --output_dir ./outputs/multimer \
    --jax_param_path openfold/resources/params/params_model_1_multimer_v3.npz &
