### ISSUE TITLE
Release Preprocessed Data/Trained Model/Eval Set

### ISSUE THREAD

**Issue by minhtuev** [aqlaboratory/openfold#85]
Hi - just a quick question, do you release the preprocessed data/trained model/eval set? We are trying to run AlphaFold/OpenFold but each protein is taking us around 3 minutes and we want to process as many of them as possible.

**Comment by gahdritz** [comment]
Not quite yet, but we will---as soon as we've retrained OpenFold from scratch (which takes a while), we plan to release the training data.

**Comment by minhtuev** [comment]
@gahdritz : thank you! Do you have an estimated timeline for this?

**Comment by gahdritz** [comment]
Weeks at least.
