### ISSUE TITLE
Severe memory fragmentation

### ISSUE THREAD

**Issue by gahdritz** [aqlaboratory/openfold#9]
In some cases, especially for larger crop sizes, intermediate tensors during training grow so large that PyTorch OOM's despite having allocated as little as 60% of available GPU memory. It would be good to carefully the profile the network to identify the worst culprit modules and come up with clean ways to prevent such degenerate tensor allocation.

**Comment by gahdritz** [comment]
Update: calling torch.cuda.empty_cache() between blocks of the extra MSA stack helps somewhat, but there's still a long way to go on this.

**Comment by lhatsk** [comment]
I guess this will affect the fine-tuning stage the most, right? Have you tried the fine-tuning configuration? I get OOMs on a 32GB card following the configuration on page 43 in the supplement (batch size = 1).

**Comment by gahdritz** [comment]
Yeah, the fine-tuning configuration is pretty rough without JAX's static memory allocation. Try enabling the cache clearing hack for the Evoformer too.

Where exactly in the network are you OOM'ing? We've been implementing a bunch of low-memory versions of the modules recently, so we might be able to help you out.

**Comment by lhatsk** [comment]
Here: self.msa_att_row(m, z=z, mask=msa_mask, chunk_size=chunk_size)

RuntimeError: CUDA out of memory. Tried to allocate 11.25 GiB (GPU 0; 31.75 GiB total capacity; 15.35 GiB already allocated; 5.26 GiB free; 25.10 GiB reserved in total by PyTorch)

Unfortunately, clearing the cache also in the evoformer doesn't help. The OOM error moves then to the backward pass.

**Comment by gahdritz** [comment]
Ouch. Just 15.35 GB already allocated. That's a new record for memory fragmentation for us (previously it was ~60%). 

Just to confirm: this is happening in the extra MSA stack, right?

In any case, this is exactly the kind of thing we wrote low-memory attention for. Right now, it's only available for inference (but not "plugged in" yet), but once I can figure out how to refactor activation checkpointing, we'll be adding training for it too.

**Comment by lhatsk** [comment]
Yes, it's in the extra MSA stack. But I can't pin-point when and why it happens.

**Comment by gahdritz** [comment]
With the addition of our new memory-efficient attention kernels in edb7d34, I consider this fixed.
