### ISSUE TITLE
Issue about training.

### ISSUE THREAD

**Issue by zjyuan1208** [aqlaboratory/openfold#98]
When I run the train_openfold.py and the following error occurs, and I still cannot figure out how to solve it. Could you please help me?

AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

**Comment by gahdritz** [comment]
Do you have `gcc` installed and on your path?

**Comment by zjyuan1208** [comment]
Yes, I have installed gcc version 11.2.0 on my openfold env path. But it still have the same problem.

**Comment by gahdritz** [comment]
Looks like you're missing CUDA. Ignoring the stuff about torch, which usually comes bundled with its own CUDA installation, try installing it like this: https://stackoverflow.com/questions/62359175/pytorch-says-that-cuda-is-not-available

**Comment by zjyuan1208** [comment]
After I disable DeepSpeed, the error is solved. But I got a new issue.
The losses are like following:
WARNING:root:experimentally_resolved loss is NaN. Skipping...
WARNING:root:fape loss is NaN. Skipping...
WARNING:root:lddt loss is NaN. Skipping...
WARNING:root:masked_msa loss is NaN. Skipping...
WARNING:root:supervised_chi loss is NaN. Skipping...
WARNING:root:violation loss is NaN. Skipping...

And it occurs a new error like following:
AssertionError: No inf checks were recorded for this optimizer.

**Comment by gahdritz** [comment]
Hm this generally happens when you have misconfigured the trainer. It might be easier to just set up CUDA after all.
